.gitignore, README.md, Tiltfile, config/default/manager_image_patch.yaml, config/manager/manager.yaml, internal/controllers/import_controller.go, internal/controllers/import_controlller_test.go, internal/controllers/suite_test.go, internal/controllers/testdata/data.go, internal/controllers/testdata/import_sample.yaml
Added some tests and removed http package.
=> chore: tidy up the  controller

docs/adr/0000-template.md, docs/adr/0001-use-adrs.md
As a lightweight way to document decisions, we will use ADRs that will be stored in the repo.
This PR includes a template and an ADR to propose that we use ADRs.
Fixes #
**Checklist**:
=> docs: introduce adrs

.gitignore, Makefile
Minor fixes for the helm chart packaging.
Fixes #
**Checklist**:
=> Fix helm chart packaging

go.mod, internal/controllers/import_controller.go, internal/controllers/import_controller_test.go
This should make import manifest creation code a bit more structured and readable
Fixes #
**Checklist**:
=> Refactor import manifest creation

go.mod, go.sum, internal/rancher/cluster.go, internal/rancher/clusterregistrationtoken.go
Using `runtime.DefaultUnstructuredConverter` is recommended way to operate upon unstructured objects while using controller-runtime.  It also makes code more readable
**Checklist**:
=> Use default unstructured converter

docs/adr/0002-use-helm.md
We need to lean towards helm ecosystem and structure our operator code around it.
**Checklist**:
=> Propose usage of helm to structure releases

.github/workflows/release.yaml, .gitignore, Makefile, hack/make-release-notes.sh
kind/feature
This PR is implementing support for publishing charts with [chart-releaser](https://github.com/helm/chart-releaser) tool. Additionally adds auto release note generation for each release based on CAPI [release/note](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/release/notes.go) tool.
Here is an example release created by this workflow: https://github.com/Danil-Grigorev/rancher-turtles/releases/tag/rancher-turtles-1.2.20, might be good to have labeling on PRs similar to CAPI operator or CAPI. 
Additionally it removes `rancher-turtles-components.yaml` file created with each release, as there is no need for that in rancher-turtles opposed to CAPI operator.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
=> ✨ Use helm chart releaser and generate notes on each release

docs/adr/0003-deletion-strategy.md
Adds deletion strategy ADR
Fixes #63 
**Checklist**:
=> 📖 Add deletion strategy ADR

Makefile, charts/rancher-turtles/templates/rancher-turtles-components.yaml
kind/cleanup
#60 early merge missed some minor chart updates
- Added missing chart updates.
- Separates release-chart makefile task into build and verify phases.
Fixes #
**Checklist**:
=> 🌱 Update generated charts output

hack/ensure-golangci-lint.sh, hack/ensure-kubectl.sh, hack/make-release-notes.sh, hack/utils.sh, internal/controllers/import_controller.go, internal/controllers/import_controller_test.go, internal/controllers/suite_test.go, internal/controllers/testdata/data.go, internal/rancher/cluster.go, internal/rancher/cluster_test.go, internal/rancher/clusterregistrationtoken.go, internal/rancher/clusterregistrationtoken_test.go, internal/rancher/suite_test.go, internal/test/cleanup.go, internal/test/crdbuilder.go, internal/test/envtest.go, main.go, scripts/go-install.sh, scripts/turtles-dev.sh, util/annotations/helpers.go, util/annotations/helpers_test.go, util/naming/name_converter.go, util/naming/name_converter_test.go, util/predicates/cluster_predicates.go, util/predicates/cluster_predicates_test.go
kind/cleanup
Align/add copyright headers in all files of the repo
Fixes #
**Checklist**:
=> 🌱 Add copyright headers to all files

README.md, code-of-conduct.md
Adds Code of conduct document to the repo
Fixes #
**Checklist**:
=> 📖 Add code of conduct 

docs/adr/0005-rancher-integration-strategy.md, docs/adr/0006-import-strategy.md
Documents the decision around our integration with Rancher
Fixes #64
=> docs: rancher integration strategy adr

.github/workflows/e2e-long.yaml, .github/workflows/e2e-short.yaml, test/e2e/data/rancher/nginx-ingress.yaml, test/e2e/e2e_suite_test.go
A minor fix for e2e workflows, run full e2e suite on push and nightly and short suite only for PR.
Fixes #
**Checklist**:
=> Split E2E test workflows

internal/controllers/import_controller.go
This adds a label when we create the Rancher cluster.
Fixes #127 
**Checklist**:
=> feat: add label to Rancher cluster when we create it

charts/rancher-turtles/templates/core-provider.yaml
This change enable the machine pool feature by default for the core provider.
Fixes #151 
**Checklist**:
=> feat: enable machine pools

.github/workflows/release.yaml
Remove `https://` from the prime registry endpoint for Docker build.
Fixes #
**Checklist**:
=> fix: remove https:// from prime registry endpoint

.github/workflows/release.yaml
Remove `https://` from prime registry endpoint: v2 - remove unneeded `echo`.
Fixes #
**Checklist**:
=> fix: remove https:// from prime registry endpoint v2

Makefile
Fixes https://github.com/rancher-sandbox/rancher-turtles/issues/170
**Checklist**:
=> Remove support for unsupported architectures

test/e2e/suites/import-gitops/import_gitops.go, test/e2e/suites/import-gitops/import_gitops_test.go
kind/bug
Additional space in embed annotation causes EKS test to fail. Needed to get nightly green again
Fixes #
**Checklist**:
=> 🐛 Fix typo in aws EKS embed

.github/workflows/e2e-long.yaml
=> Send alert to slack if e2e run fails

.github/workflows/e2e-long.yaml
A small change to allow us to run the full e2e on demand.
Fixes #
**Checklist**:
=> feat: add ability to manually invoke the full e2e

.github/workflows/nightly-chart-and-image-publish.yaml
=> Publish chart as OCI image to GHCR and Prime Registry

.github/workflows/release.yaml
Fixes issue while releasing Helm chart with missing environment variable, digest and depedencies.
Fixes #
**Checklist**:
=> chore: add cr_token env variable to helm release action

.github/workflows/release.yaml
Removing references to prod registry endpoint secret.
Fixes #
**Checklist**:
=> chore: remove references to prod registry endpoint secret

.github/workflows/codeql.yml, .github/workflows/trivy.yml
This enabled trivy image scanning.
Fixes #221 
**Checklist**:
=> chore: add code &  image scanning

.github/workflows/e2e-long.yaml, .github/workflows/janitor.yaml
This change enables the azure janitor to perform the delete instead of just reporting what it would delete.
Fixes #237 
**Checklist**:
=> chore: enable janitor to make changes

.github/workflows/test_chart.yaml
Bumping chart-testing-action to 2.6.0 to include latest version of cosign
Fixes #
**Checklist**:
=> 🌱 Bumb: chart-testing-action to 2.6.0

.github/workflows/release-workflow.yml, .github/workflows/release.yaml
=> Fix image resolution for ghcr

.github/workflows/release-workflow.yml, .github/workflows/release.yaml
Fix image resolution for ghcr
Fixes #
**Checklist**:
=> Fix for variable name

.github/workflows/release-workflow.yml, .github/workflows/release.yaml, .github/workflows/release_sign/action.yaml
This caused image signature verification issue during v0.3.0 release and multiarch image publish (TIL).
Fixes #
**Checklist**:
=> 🐛 Fix issuer value for signature verification

test/e2e/const.go, test/e2e/suites/import-gitops/import_gitops_test.go
Changes the label on the AWS test so its not run
Fixes #
**Checklist**:
=> chore: change e2e label for aws test

charts/rancher-turtles/templates/rancher-turtles-components.yaml, config/rbac/role.yaml, internal/controllers/import_controller.go, internal/controllers/import_controller_test.go, internal/controllers/suite_test.go, internal/rancher/management/v3/clusterregistrationtoken.go
Implements #264 
Fixes #
**Checklist**:
=> ✨Place all rancher objects in the CAPI namespace

.github/workflows/nightly-chart-and-image-publish.yaml
This PR simplifies and fixes failing nightly helm chart publishing job.
Fixes #
**Checklist**:
=> :bug: Fix failing nightly chart publish job

.github/workflows/nightly-chart-and-image-publish.yaml
=> Print helm install command after publishing nightly chart

.github/workflows/nightly-chart-and-image-publish.yaml
=> Fix helm chart tag in nightly build

.gitignore, devbox.json, devbox.lock
Adds devbox configuration which pins go to th eversion we use.
Fixes #
**Checklist**:
=> chore: add devbox

docs/adr/0007-rancher-turtles-public-api.md
=> :book: Add ADR on on the rancher turtles API CR

.github/dependabot.yaml
This should allow dependencies to be grouped inside a single PR, and patch releases bumps for the upstream libraries.
Fixes #
**Checklist**:
=> ✨Refactor dependabot to submit group updates

.github/workflows/e2e-long-test.yaml
Allow setting the ginkgo labels
Fixes #
**Checklist**:
=> test: allow setting ginkgo labels

charts/rancher-turtles/templates/rancher-turtles-components.yaml, config/rbac/role.yaml, go.mod, internal/controllers/capiprovider_controller.go, internal/sync/client.go, internal/sync/client_test.go, internal/sync/core.go, internal/sync/core_test.go, internal/sync/interface.go, internal/sync/interface_test.go, internal/sync/suite_test.go, internal/test/helpers/envtest.go, main.go
Part of #286 
Depends on #288 
**Checklist**:
=> ✨ Providers api controller

test/e2e/suites/import-gitops/suite_test.go
=> test: install additional capi providers when label isn't just short tests

.github/workflows/e2e-long.yaml, .github/workflows/run-e2e-suite.yaml
Refactors the e2e test suite to use reseuable workflow
Fixes #
**Checklist**:
=> refactor: change e2e tests to use reuseable workflow

.github/workflows/e2e-long.yaml, .github/workflows/run-e2e-suite.yaml
Move the env vars from the parent into the reuseable workflow
Fixes #
**Checklist**:
=> fix: set env vars in reuseable workflow

.github/dependabot.yaml
Changes the dependabot configuration on the ignored dependencies as some updates as still coming through
Fixes #
**Checklist**:
=> chore: change the ignore dependabot updates

Makefile, hack/ensure-kubectl.sh, test/e2e/specs/import_gitops.go, test/e2e/suites/update-labels/update_labels_test.go, test/e2e/suites/v2prov/v2prov_test.go, test/framework/rancher_helpers.go, test/testenv/cleanup.go
kind/chore
Fixes #333 
**Checklist**:
=> 🌱 Implement full cluster artifact gathering for both clusters after each test run

.github/workflows/e2e-long.yaml
=> :bug: Slow down nightly schedule 2 times, to prevent hitting data limit

docs/release.md
This patch adds a release docs with details on branching, versioning, support and guarantees, release cadence and step-by-step guidance on how to cut a release/push tag and open a PR in this / rancher-turtles-docs repos.
Fixes #345 
**Checklist**:
=> 📖 Add release docs to Rancher Turtles repo

scripts/turtles-dev.sh
Tilt environment was failing to run `rancher-turtles-controller` because some of the pre-install operations performed when using `helm install` were not applied. To compensate for this, the script that creates the development environment is now updated to install `cluster-api-operator` (together with `cert-manager`) and default to `rancher:v2.8.1`.
Fixes #
As a follow-up, we should also add a test case that covers the development environment #339.
**Checklist**:
=> chore: update development environment script

test/e2e/data/capi-operator/full-providers.yaml
=> WIP: Pin provider versions

charts/rancher-turtles/templates/post-delete-job.yaml, charts/rancher-turtles/templates/pre-install-job.yaml, charts/rancher-turtles/values.yaml
This PR adds a post-delete hook to the helm chart for taking care of Rancher Turtles extension deletion properly
Fixes #409 
Documentation PR: https://github.com/rancher-sandbox/rancher-turtles-docs/pull/62
**Checklist**:
=> ✨ Add post-delete helm hook for RT extension deletion process

docs/adr/0009-use-structured-proxy-types.md
ADR around the benefits of using structured proxy types
Adresses #113
**Checklist**:
=> 📖 Add ADR around use of structured proxy types

.github/workflows/dependabot.yml
This will ensure any diff created by make generate is committed with dependabot bumps.
Fixes #
**Checklist**:
=> 🌱 Create dependabot.yml to run make generate on each dependabot PR

charts/rancher-turtles/Chart.yaml
When documenting the installation via Rancher UI, I noticed the name of the Chart need to be changed to `Rancher Turtles - the Cluster API Extension`.
Fixes #
**Checklist**:
=> chore: edit chart display name

charts/rancher-turtles/templates/clusterctl-config.yaml
Due to rancher 2.8.3 still using 1.4.6 CAPI version, we will use this by default too.
Fixes #
**Checklist**:
=> 🌱 Downgrade CAPI to 1.4.6

charts/rancher-turtles/templates/core-provider.yaml
This makes changes to the resource created by the hooks to fix issues with upgrading and to make uninstall cleaner. Specifcally:
- Check if the namespace already exists
- Use the pre-delete hook to help uninstall the resources
Fixes #455 
**Checklist**:
=> fix: chart changes for upgrade and uninstall

charts/rancher-turtles/questions.yml
Exclude namespace selection from UI view.
Fixes #462 
**Checklist**:
=> :bug: Exclude namespace selection from questions.yaml

docs/release.md
Improves release process notes with Ruleset Disabling orders and few minor typos
Fixes #
**Checklist**:
=> 📖 Improve release docs

.github/workflows/nightly-test-release.yaml, .github/workflows/release.yaml, Makefile, hack/ensure-golangci-lint.sh, scripts/image-digest.sh
Based on of the discussions, it was decided to remove s390x arch from release artifacts 
Fixes #
**Checklist**:
=> :chore: Remove s390x architecture from release packages

scripts/turtles-dev.sh
Required for: https://github.com/rancher/turtles-docs/pull/85
**Checklist**:
=> Update dev-env script

.github/workflows/e2e-short-test.yaml
Changed the testing workflow to use the org level runners.
Fixes #
**Checklist**:
=> chore: trying to use the org level runners

.github/workflows/e2e-short-test.yaml
Should've replaced the tokens on the first attempt, doh!
Fixes #
**Checklist**:
=> chore: replace the tokens

charts/rancher-turtles/templates/core-provider.yaml, charts/rancher-turtles/templates/rke2-bootstrap.yaml, charts/rancher-turtles/templates/rke2-controlplane.yaml, charts/rancher-turtles/values.yaml
=> Add helm chart value to override CAPI images

charts/rancher-turtles/values.yaml, feature/feature.go
This changes the label propagation so that its enabled by default. 
Fixes #
**Checklist**:
=> chore: enable label propogation by default

.github/workflows/dependabot.yml, .github/workflows/nightly-test-release.yaml
rancher/highlander#89
Fixes #
**Checklist**:
=> Replace github commit/push actions with manual steps

charts/rancher-turtles/questions.yml, internal/controllers/import_controller.go, internal/controllers/import_controller_test.go, internal/controllers/import_controller_v3.go, internal/controllers/import_controller_v3_test.go
Continously propagate labels to Rancher cluster
Fixes https://github.com/rancher/turtles/issues/540
**Checklist**:
=> Continously propagate labels to Rancher cluster

charts/rancher-turtles/templates/clusterctl-config.yaml, exp/etcdrestore/go.mod, exp/etcdrestore/go.sum
=> Bump CAPRKE2 to v0.3.0

api/v1alpha1/capiprovider_types.go, api/v1alpha1/provider_types.go, charts/rancher-turtles/templates/rancher-turtles-components.yaml, config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
=> Add ipam and runtimeextension providers

charts/rancher-turtles/questions.yml, charts/rancher-turtles/values.yaml, feature/feature.go, internal/controllers/suite_test.go
=> Mark propagate labels as experimental

docs/release.md
With the [updates](https://github.com/rancher/turtles-docs/pull/109) to the release workflow, involving the creation of PR against docs repository, we need to update release docs to reflect the change.
Fixes #
**Checklist**:
=> :book: Updated documentation release steps

test/e2e/data/cluster-templates/docker-rke2.yaml
=> Bump RKE2 API version in E2E

charts/rancher-turtles/templates/core-provider.yaml, charts/rancher-turtles/templates/rke2-bootstrap.yaml, charts/rancher-turtles/templates/rke2-controlplane.yaml, charts/rancher-turtles/values.yaml
Cherry-pick for #533
Fixes #532 
**Checklist**:
=> chore: Fix imageUrl override to allow air-gapped turtles helm chart setup

docs/adr/0011-v1-to-v3-migration.md
ADR on automatic migration procedure for `provisioning.cattle.io/v1` clusters to `management.cattle.io/v3` clusters.
Fixes #
**Checklist**:
=> 📖 ADR: v1-v3 automatic migration

README.md
Replaces https://github.com/rancher/turtles/pull/552 due to inactivity
Fixes #
**Checklist**:
=> Update getting started guide reference

test/e2e/suites/embedded-capi-disabled-v3/suite_test.go
=> Fix gitea service type in E2E

internal/controllers/import_controller_v3.go, internal/controllers/import_controller_v3_test.go, main.go, util/util.go
Fixes: #589 
Fixes #
**Checklist**:
=> Perform cache-less check on imported annotation for CAPI cluster

charts/rancher-turtles/templates/clusterctl-config.yaml
Fixes issue: https://github.com/rancher-sandbox/cluster-api-addon-provider-fleet/issues/84
Fixes #
**Checklist**:
=> Bump CAAPF to v0.3.1

.github/workflows/dependabot.yml
=> Dependabot fix - check if make generate produced changes

.github/workflows/dependabot.yml
Followup on #644 which ensures we don’t commit empty changes
Fixes #
**Checklist**:
=> Ensure we don't commit empty changes with dependabot generate

.github/workflows/dependabot.yml
Followup on #645 and #644 as it didn’t have the sufficient changes to ensure dependabot generated code gets into PR content.
The updated files need to be pushed, if there is an existing change. Otherwise `git push` does not error out if there is nothing to push.
Fixes #
**Checklist**:
=> Push generated code

charts/rancher-turtles/templates/clusterctl-config.yaml, test/e2e/data/capi-operator/capi-providers.yaml, test/e2e/data/capi-operator/capv-provider.yaml, test/e2e/data/capi-operator/full-providers.yaml
=> Bump CAPI infra providers versions

test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go, test/e2e/suites/import-gitops/import_gitops_test.go
This change re-enables AKS e2e tests back after recent changes and fixes.
Fixes #661 
**Checklist**:
=> 🌱 Re-enable AKS e2e

docs/release.md
=> Update release docs with test package tag

test/e2e/suites/chart-upgrade/chart_upgrade_test.go, test/e2e/suites/chart-upgrade/suite_test.go, test/e2e/suites/import-gitops/suite_test.go
=> Perform chart upgrade test separately

test/e2e/data/capi-operator/capz-identity-secret.yaml, test/e2e/data/cluster-templates/azure-aks-mmp.yaml
=> Fix secret namespace for CAPZ in E2E

.github/workflows/e2e-long-test.yaml, .github/workflows/e2e-long.yaml, .github/workflows/janitor.yaml, .github/workflows/run-e2e-suite.yaml
=> Bump azure janitor version

charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml, exp/etcdrestore/config/default/kustomization.yaml, exp/etcdrestore/config/webhook/manifests.yaml, exp/etcdrestore/main.go, exp/etcdrestore/webhooks/install.sh, exp/etcdrestore/webhooks/installsh.go, exp/etcdrestore/webhooks/rke2config.go, exp/etcdrestore/webhooks/rke2config_test.go, tilt-settings.json.example, tilt/project/Tiltfile
- Add system-agent installation script to etcd restore, it's a modified version of https://github.com/rancher/system-agent/blob/main/install.sh, we should make some changes in system-agent repo and also use this script so don't have to duplicate efforts, for now, let's have our version to not block development.
- Fix webhook configuration
- Add insecure skip verify to etcd restore webhook and also tilt support for it
Fixes https://github.com/rancher/turtles/issues/497
**Checklist**:
=> Add system-agent installation script to etcd restore

charts/rancher-turtles/templates/clusterctl-config.yaml
Part of https://github.com/rancher/turtles/issues/548
=> Add Elemental infra provider

charts/rancher-turtles/templates/clusterctl-config.yaml, exp/etcdrestore/go.mod, exp/etcdrestore/go.sum
=> Bump CAPRKE2 to v0.6.1

exp/etcdrestore/webhooks/rke2config.go
=> Add turtles annotation to RKE2Config modified by webhook

charts/rancher-turtles/Chart.yaml, exp/etcdrestore/go.mod, exp/etcdrestore/go.sum, go.mod, go.sum, test/go.mod, test/go.sum
Update CAPI Operator to version 0.13, bringing clusterctl.yaml fixes for support of image overrides.
Fixes #
**Checklist**:
=> Update CAPI Operator version to v0.13.0

charts/rancher-turtles/templates/clusterctl-config.yaml
=> Use forks as source for CAPI manifests

Makefile
=> Fix make command for pushing e2e image

.github/workflows/release_build/action.yaml
Ensures digest is correctly passed and set as an output for the release_build GHA.
Nightly Release action started failing after https://github.com/rancher/turtles/commit/5e6feaed3d683c5fd66f2914ddf363e9f8a90bb3 and that removes  `id` being set  but it is needed for the outputs of the release_build action:
```
outputs:
digest:
description: "Image digest"
value: ${{ steps.image_info.outputs.digest }}
image:
description: "Image name"
value: ${{ steps.image_info.outputs.image }}
```
Since digest is not properly passed, release workflow fails running cosign command:
```
cosign sign --yes ghcr.io/***/turtles@ --oidc-provider=github-actions --recursive
cosign verify ghcr.io/***/turtles@ --certificate-identity=https://github.com/***/turtles/.github/workflows …
```
=> 🐛 Fix: Ensure digest is correctly passed and set as an output

.github/workflows/run-e2e-suite.yaml
Integrates GCP janitor with turtles.
Test run: https://github.com/Danil-Grigorev/rancher-turtles/actions/runs/10961090406
Fixes #749 
**Checklist**:
=> Integrate GCP janitor to the e2e

exp/etcdrestore/go.mod, exp/etcdrestore/go.sum, internal/controllers/clusterctl/config.yaml, scripts/turtles-dev.sh
Bumping to latest CAPRKE2 version https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.7.0
Fixes #
**Checklist**:
=> Bump CAPRKE2 to v0.7.0

.github/workflows/janitor.yaml
Change janitor repo values: rancher-sandbox to rancher
Fixes - Failing janitor action https://github.com/rancher/turtles/actions/runs/11452606748
**Checklist**:
=> Update janitor repo values

.github/ISSUE_TEMPLATE/certification_request.yaml
Fix wrong placeholder in certification provider request issue template.
Fixes #
**Checklist**:
=> chore: fix provider url placeholder

.github/workflows/run-e2e-suite.yaml
This should unblock execution of e2e test for further failures investigation.
Fixes #
**Checklist**:
=> 🌱 Switch org for gcp-janitor

.github/workflows/dependabot.yml
Attempt to sign dependabot commits to pass the signature check.
Fixes #
**Checklist**:
=> 🌱 Sign dependabot commits

updatecli/updatecli.d/manifest.yaml
Updatecli needs to keep CAPD in sync with the version of the CAPI core.
Fixes #
**Checklist**:
=> 🌱 Run updatecli for CAPD for versioning consistency

test/e2e/specs/import_gitops_mgmtv3.go, test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
=> Disable e2e verification for NoCreatorRBAC annotation in AWS and Azure

.github/workflows/run-e2e-suite.yaml
=> Fix slack notifications action

internal/controllers/clusterctl/config.yaml
Revert azure override until we build Azure Service Operator
Fixes #
**Checklist**:
=> Revert azure image override

Dockerfile, Makefile, Tiltfile, charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml, exp/etcdrestore/config/default/manager_image_patch.yaml, scripts/turtles-dev.sh, test/e2e/config/operator.yaml, test/e2e/specs/import_gitops_mgmtv3.go, test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
This is a backport of https://github.com/rancher/turtles/pull/897 and https://github.com/rancher/turtles/pull/899
Fixes #
**Checklist**:
=> [release-0.14] Backport etcd image and RBAC

.github/workflows/run-e2e-suite.yaml, Makefile
Fixes missing image build and push to nightly job post #902, tested on https://github.com/rancher/turtles/actions/runs/12157758760/job/33904244827
Fixes #
**Checklist**:
=> Fix nightly e2e image push in workflow

.github/workflows/release-workflow.yaml, .github/workflows/release.yml
Due to the security team's requirements for unifying Rancher SLSA compliance processes, we need to rename the release workflow. The tool they use to verify requires it to be called `release.yml` https://github.com/rancherlabs/slsactl/blob/main/internal/verify/verify.go#L88. Naming is also described in one of the internal docs.
Fixes #
**Checklist**:
=> Rename release workflow

.github/workflows/codeql.yml, .github/workflows/dependabot.yml, .github/workflows/e2e-short.yaml, .github/workflows/golangci-lint.yml, .github/workflows/lint.yaml, .github/workflows/nightly-chart-and-image-publish.yaml, .github/workflows/nightly-test-release.yaml, .github/workflows/release-workflow.yaml, .github/workflows/release_build/action.yaml, .github/workflows/run-e2e-suite.yaml, .github/workflows/test_chart.yaml, Makefile, exp/etcdrestore/go.mod, go.mod, go.work.example, test/go.mod
This should fix a bunch of security alerts
Fixes #
**Checklist**:
=> Bump golang to 1.22.10

.github/workflows/nightly-test-release.yaml
=> Nightly release job workflow path fix

.github/workflows/nightly-test-release.yaml
We are performing sign process as a part of the `release.yaml` workflow, so this was added by mistake.
Fixes #
**Checklist**:
=> 🐛 Remove duplicate sign in nightly-test-release.yaml

.github/workflows/run-e2e-suite.yaml
This PR should fix the workflow that I accidentally broke with the last PR :(
=> Fix e2e workflow syntax

.golangci.yml
=> Change year requirement in file headers

.github/dependabot.yaml
Enable dependabot for exp/clusterclass to track security fixes in timely manner.
Fixes #
**Checklist**:
=> Add exp/clusterclass to dependabot.yaml

.github/dependabot.yaml
Added missing double quote to fix https://github.com/rancher/turtles/runs/35645547641
Fixes #
**Checklist**:
=> fix: Add missing double quote

internal/controllers/clusterctl/config.yaml
=> Disable image override for ASO

charts/rancher-turtles/questions.yml, charts/rancher-turtles/values.yaml
=> Add feature stages to helm chart

exp/clusterclass/internal/controller/clusterupgradegroup_controller.go, internal/controllers/import_controller_v3_test.go
=> 🌱 Fix linter warnings

docs/release.md
Document the format used to tag a release candidate.
Fixes #
**Checklist**:
=> docs: add rc to release guide

test/go.mod
Using a fixed version helps to resolve import error, the modules get replaced anyway by `replace` above.
Fixes https://github.com/rancher/turtles/issues/981
**Checklist**:
=> Use fixed version of local modules in e2e suite

docs/release.md
To keep Turtles Docs repo tags consistent with semantic versioning scheme, updating the release notes
Fixes #
**Checklist**:
=> 📖 Use semantic versioning scheme for Turtles Docs repo tags

Tiltfile, tilt/project/Tiltfile
=> Allow setting custom args for projects in Tiltfile

charts/rancher-turtles/questions.yml, charts/rancher-turtles/templates/deployment.yaml, charts/rancher-turtles/templates/rancher-turtles-components.yaml, charts/rancher-turtles/templates/ui-plugin.yaml, charts/rancher-turtles/values.yaml, config/rbac/role.yaml, docs/adr/0014-turtles-ui-installation.md, feature/feature.go, internal/controllers/uiplugin_controller.go, main.go, updatecli/updatecli.d/manifest.yaml
=> Install CAPI UI extension for development

test/e2e/config/operator.yaml, test/e2e/data/cluster-templates/aws-eks-mmp.yaml, test/e2e/data/cluster-templates/azure-aks-topology.yaml, test/e2e/data/cluster-templates/docker-kubeadm.yaml, test/e2e/data/cluster-templates/docker-rke2.yaml, test/e2e/data/cluster-templates/gcp-gke.yaml, test/e2e/data/cluster-templates/vsphere-kubeadm.yaml, test/e2e/data/cluster-templates/vsphere-rke2.yaml
This PR bumps both RKE2/Kubeadm vsphere templates to the latest CSI/CPI versions and introduces namespace variable to templates
Fixes #
**Checklist**:
=> Update e2e templates

test/e2e/specs/import_gitops_mgmtv3.go, test/e2e/suites/v2prov/v2prov_test.go, test/framework/rancher_helpers.go
=> Wait for rancher kubeconfig to be fetched in e2e

test/e2e/data/cluster-templates/docker-rke2.yaml
Just an attempt to fix the e2e broken test
=> Fix docker rke2 e2e template

examples/applications/azure/clusterresourceset-cloud-provider.yaml, examples/clusterclasses/azure/clusterclass-example.yaml
This is a ClusterClass generic example for RKE2 on Azure.
It allows the user to provision a simple cluster using Community images.
It supports generic but sizeable MachineDeployments.
Fixes #
**Checklist**:
=> Add Azure + RKE2 ClusterClass example

scripts/turtles-quickstart.sh
=> Add Rancher Turtles quickstart script

go.work.example, test/e2e/README.md
Just a bit more input on how to correctly setup the e2e workspace.
Also removing the `go.work.example` since it can be generated instead.
=> 📖 Clarify e2e workspace setup

scripts/turtles-quickstart.sh
=> Fixing Rancher condition check when Ngrok

test/e2e/config/operator.yaml, test/e2e/data/cluster-templates/aws-ec2-kubeadm.yaml, test/e2e/data/cluster-templates/docker-kubeadm.yaml, test/e2e/data/cluster-templates/docker-rke2.yaml, test/e2e/data/cni/kindnet.yaml, test/e2e/specs/etcd_snapshot_restore.go, test/e2e/specs/import_gitops_mgmtv3.go, test/e2e/suites/etcd-snapshot-restore/etcd_snapshot_restore_test.go
Switch CAPD+RKE2 e2e template to clusterclass
Fixes https://github.com/rancher/turtles/issues/1150
**Checklist**:
=> Switch CAPD+RKE2 e2e template to clusterclass

.github/workflows/ensure-issues-labels-desc.yaml, .github/workflows/ensure-pr-labels.yaml
This PR adds 2 workflows to ensure all our PRs and Issues will have `area/*` label and Issues will have a description. Both workflows were tested on my fork.
Fixes https://github.com/rancher/turtles/issues/1167
**Checklist**:
=> Ensure PR/Issues have labels and description

.github/dependabot.yaml
This PR introduces a testing group for ginkgo and gomega, providers group, and changes all updated to weekly.
Fixes #
**Checklist**:
=> Organize dependabot groups

charts/rancher-turtles/values.yaml, updatecli/updatecli.d/manifest.yaml
Fixes CAPI UI extension installation with turtles chart. Releases are in format [capi-0.8.2](https://github.com/rancher/capi-ui-extension/releases/tag/capi-0.8.2)
Fixes #1207 
**Checklist**:
=> CAPI-UI installation fix

internal/controllers/clusterctl/config.yaml
Manually bump version to latest, to avoid issues with CI on updatecli 
Fixes #
**Checklist**:
=> Bump CAAPF to version `v0.7.4`

docs/release.md
Minor fix to remove a channel no longer in use.
=> Remove unused release channel reference

.github/workflows/trivy.yml
The version of Ubuntu used to execute this workflow has been deprecated.
Fixes #
https://github.com/actions/runner-images/issues/11101
**Checklist**:
=> :seedling: Update trivy CI workflow to use `ubuntu-latest` image

examples/clusterclasses/vsphere/clusterclass-rke2-example.yaml, examples/examples.go, test/e2e/const.go, test/e2e/data/cluster-templates/vsphere-rke2-topology.yaml, test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go, test/framework/fleet_helper.go
Updated CAPV+RKE2 test to use clusterclass.
Fixes #1156 
**Checklist**:
=> :seedling:  Update CAPV+RKE2 test to use clusterclass

test/e2e/specs/import_gitops_mgmtv3.go, test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
This PR cleans up a bit additional fleet repos creation
Fixes #
**Checklist**:
=> Create Fleet git repo in spec instead of suite

test/e2e/data/cluster-templates/vsphere-rke2-topology.yaml, test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Fixed package imports to get CAPV tests to compile again. Also changed CAPV+RKE2 template to use RKE2_VERSION env var. 
**Checklist**:
=> :seedling: Fix CAPV CI failure

scripts/turtles-quickstart.sh
=> Update turtles-quickstart.sh script

scripts/turtles-quickstart.sh
=> Add CLUSTER_CLASS_NAME required var to turtles-quickstart.sh

examples/clusterclasses/azure/clusterclass-rke2-example.yaml, test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
- Remove variables affecting cluster class templating process and preventing further cluster scaling.
- Replace imageVersion with automatic jsonPatch based on builtin cluster version.
- Use default registration method to allow later change to control-plane-endpoint
Fixes #
**Checklist**:
=> Allow CAPZ cluster replicas change using example template

internal/controllers/clusterctl/config.yaml
This reverts commit aa6f3c0ad7437e21e30310501e52d46283ebac0c.
Seems that the newest `v2.12.0` image is published correctly:
```bash
skopeo list-tags docker://registry.suse.com/rancher/azureserviceoperator
{
"Repository": "registry.suse.com/rancher/azureserviceoperator",
"Tags": [
"sha256-2560c1accbf3215880d482c2382743d7064685de8a8d58a4a3ec66cdb4862207.sig",
"sha256-3e56806a960689e502c81a2c9be2ec876edc7efeb64f1db09c528ebc2ed92603.sig",
"sha256-62539aad08500d22bee15508358bc55e7a57227c99e2845705d29feeba74de99.sig",
"sha256-783a6d6c534d3e3d4d96dfc85a0b95723a313625b5c5f52b17ecbbba60780fc6.sig",
"sha256-80f0973513e02ccd37e5145b0e889b8fb50d2df2ea44fb033e12dec9a40f40c2.att",
"sha256-80f0973513e02ccd37e5145b0e889b8fb50d2df2ea44fb033e12dec9a40f40c2.sig", …
```
=> Revert "Disable image override for ASO (#1040)"

test/e2e/const.go
=> 🌱 Docker const values cleanup

test/e2e/data/cluster-templates/docker-kubeadm-topology.yaml, test/e2e/data/cluster-templates/docker-rke2-topology.yaml
=> Remove unused label from Docker clusters

.github/workflows/e2e-long.yaml
Increases the e2e nightly run to once a day, which will make it easier to correlate failures to commits.
Fixes #
**Checklist**:
=> Run e2e nightly every day

exp/day2/go.mod, exp/day2/go.sum, internal/controllers/clusterctl/config.yaml
as title: https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.14.0
Fixes #
**Checklist**:
=> 🌱 Bump CAPRKE2 to v0.14.0 latest release

docs/release.md
Noticed it while cutting another rc release 
Fixes #
**Checklist**:
=> 📖 Fix release GHA reference in release docs

charts/rancher-turtles/values.schema.json, charts/rancher-turtles/values.yaml
Add helm chart values validation by utilizing values.schema.json https://helm.sh/docs/topics/charts/#schema-files
Fixes #
**Checklist**:
=> Add helm chart values validation

charts/rancher-turtles/questions.yml, charts/rancher-turtles/templates/addon-provider-fleet.yaml, charts/rancher-turtles/templates/deployment.yaml, charts/rancher-turtles/values.yaml, feature/feature.go, internal/controllers/import_controller_v3.go, internal/controllers/suite_test.go
By promoting addon-provider-fleet to GA, the feature cannot be disabled and the feature gate is no longer required.
Fixes #1317 
Related docs PR: https://github.com/rancher/turtles-docs/pull/288
**Checklist**:
=> :seedling:  Promote addon-provider-fleet feature to GA

examples/applications/ccm/aws-helm/helm-chart.yaml
There is no CPI release for each k8s, so having a fixed version is safer.
Fixes #
**Checklist**:
=> Use fixed image tag for AWS CPI

api/v1alpha1/capiprovider_types.go, charts/rancher-turtles/templates/rancher-turtles-components.yaml, config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
Issue: https://github.com/rancher/turtles/issues/968
Fixes #
**Checklist**:
=> Add oci option to fetchConfig validation

examples/applications/cni/calico/helm-chart.yaml
Should fix the e2e failing tests
Fixes #
**Checklist**:
=> Pin Calico chart to v3.29.3

.github/workflows/codeql.yml, .github/workflows/dependabot.yml, .github/workflows/e2e-image-publish.yaml, .github/workflows/e2e-short.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/nightly-test-release.yaml, .github/workflows/release-workflow.yaml, .github/workflows/release_build/action.yaml, .github/workflows/run-e2e-suite.yaml, .github/workflows/run-vsphere-tests.yaml, .github/workflows/test_chart.yaml, Makefile, exp/clusterclass/go.mod, exp/day2/go.mod, go.mod, test/go.mod, tilt/project/Tiltfile
Bumping Golang version to address [reported vulnerabilities](https://github.com/rancher/turtles/security/code-scanning).
**Checklist**:
=> :seedling: Bump Go version to 1.23.9

examples/applications/cni/aws/calico/helm-chart.yaml
For some reason, the new version of the Calico chart fails to install on the EC2 Kubeadm cluster. This PR pins the version that works.
Fixes #
**Checklist**:
=> Pin calico chart version for AWS

.github/dependabot.yaml, examples/README.md, examples/go.mod, examples/go.sum, examples/main.go
This implementation should allow to quickly apply full example `ClusterClass` template with applications via `examples` CLI.
Fixes #1385
**Checklist**:
=> Add examples tooling

examples/README.md
Just a small tip for anyone having issues running the tool.
Fixes #
**Checklist**:
=> Suggest go workspace setup for Examples CLI Tool

internal/controllers/clusterctl/config.yaml, internal/controllers/clusterctl/config_test.go
https://github.com/rancher/cluster-api-addon-provider-fleet/releases/tag/v0.10.0
Fixes #
**Checklist**:
=> Bump CAAPF to v0.10.0

test/e2e/const.go, test/e2e/data/rancher/system-store-setting-patch.yaml, test/testenv/rancher.go
Support system store mode for kind+ngrok e2e setup. This is only needed to run tests locally using `make test-e2e`.
Fixes #
**Checklist**:
=> Support system store mode for kind+ngrok e2e setup

exp/day2/go.mod, exp/day2/go.sum, internal/controllers/clusterctl/config.yaml
Bumps caprke2 to latest release
Fixes #
**Checklist**:
=> Update to caprke2 v0.16.2

scripts/turtles-dev.sh
Bump ngrok operator for dev env.
Fixes https://github.com/rancher/turtles/issues/1260
**Checklist**:
=> Bump ngrok operator for dev env

internal/controllers/clusterctl/config.yaml
=> Bump caapf to v0.10.1

.devcontainer/devcontainer.json
Current build fails with missing `kind` source, and has outdated golang version.
Fixes #
**Checklist**:
=> Fix broken devcontainer build

exp/day2/go.mod, exp/day2/go.sum, internal/controllers/clusterctl/config.yaml
=> Bump CAPRKE2 to v0.17.0

config/capiproviders/bootstrap.yaml, config/capiproviders/controlplane.yaml, config/capiproviders/core.yaml, config/capiproviders/kustomization.yaml, scripts/turtles-dev.sh
=> Fix dev-env not deploying embedded CAPI operator

docs/adr/0015-capiprovider-architecture.md
This is 99% copy/paste of the RFD. 
I listed the three known issues relevant to implement the ADR.
The status is already accepted since work is mostly done.
Fixes #1420 
**Checklist**:
=> Add CAPIProvider architecture ADR

.github/workflows/run-vsphere-tests.yaml
=> Add vSphere e2e Slack alert on failure

test/e2e/data/capi-operator/clusterctlconfig.yaml
Fixing a mistake introduced with #1550
Fixes #
**Checklist**:
=> Fix capd e2e test image override

tilt/project/Tiltfile
=> Mount clusterctl cm in Tilt environment

test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go, test/testenv/operator.go
Temporary workaround to make e2e suite more stable until ASO is bumped upstream
Test run https://github.com/rancher/turtles/actions/runs/16774568196
Fixes #
**Checklist**:
=> Wait for ASO pod to be ready and restart if needed

charts/rancher-turtles/templates/post-upgrade-job.yaml
Follow up PR for https://github.com/rancher/turtles/pull/1582
Added a check to ensure that the CRD is present before attempting to update/delete it.
Fixes #
**Checklist**:
=> fix: Make post-upgrade hook idempotent

updatecli/updatecli.d/manifest.yaml
This file has been moved and the updatecli missed it in: https://github.com/rancher/turtles/pull/1597
Leading to failed tests.
Fixes #
**Checklist**:
=> Actualize updatecli manifest

scripts/turtles-quickstart.sh
=> Bump Turtles and Rancher versions for quickstart

exp/day2/go.mod, exp/day2/go.sum, go.mod, go.sum, test/go.mod, test/go.sum
No idea why dependabot insisted adding an unverified commit: https://github.com/rancher/turtles/pull/1650/commits
This is a replacement for it.
Fixes #
**Checklist**:
=> Update test dependencies

updatecli/updatecli.d/manifest.yaml
Issue: https://github.com/rancher/turtles/issues/1612
Fixes #
**Checklist**:
=> Rename config.yaml to config-default.yaml

docs/adr/0016-capi-version-pinning.md
=> ADR 0016: CAPI version pinning strategy

charts/rancher-turtles-providers/templates/addon-fleet.yaml, charts/rancher-turtles-providers/templates/bootstrap-kubeadm.yaml, charts/rancher-turtles-providers/templates/bootstrap-rke2.yaml, charts/rancher-turtles-providers/templates/controlplane-kubeadm.yaml, charts/rancher-turtles-providers/templates/controlplane-rke2.yaml, charts/rancher-turtles-providers/templates/infrastructure-aws.yaml, charts/rancher-turtles-providers/templates/infrastructure-azure.yaml, charts/rancher-turtles-providers/templates/infrastructure-docker.yaml, charts/rancher-turtles-providers/templates/infrastructure-gcp.yaml, charts/rancher-turtles-providers/templates/infrastructure-vsphere.yaml, charts/rancher-turtles-providers/values.schema.json, charts/rancher-turtles-providers/values.yaml
This PR fixes some indentation errors, add new values and documents values that don't have defaults.
Fixes #
**Checklist**:
=> Providers helm chart improvements

.github/workflows/release-v2.yaml
Adds a step that attests provenance. Mostly used https://github.com/rancher/fleet/blob/f3cecbcfef78549c5d30355970fd58a15fcad4e7/.github/workflows/release.yml#L154-L184 as a guide.
Fixes #1724
**Checklist**:
=> ci: Add attestation

.github/workflows/release-v2.yaml
Backport of https://github.com/rancher/turtles/pull/1730 to `release/v0.25`
Fixes #
**Checklist**:
=> [release/v0.25] ci: Add attestation

.github/workflows/backport-pr.yaml
=> Fix secret path for backport automation

.github/workflows/backport-pr.yaml
Reverts: https://github.com/rancher/turtles/commit/23fe1c7c1ee79889b1cf1a0d93d2de5a843df0db, path should include secret/data https://github.com/rancherlabs/eio/issues/3626#issuecomment-3332561085
Fixes #
**Checklist**:
=> Use proper path for backport secrets

charts/rancher-turtles/values.yaml
Follow-up to: https://github.com/rancher/turtles/pull/1783 to cleanup leftover clusterclass-operations from values.yaml
Fixes #
**Checklist**:
=> remove clusterclass-operations from values.yaml
