rancher/turtles

- go.mod
- go.sum
- internal/ranchercluster/ranchercluster.go
- internal/ranchercluster/ranchercluster_test.go
- internal/ranchercluster/suite_test.go
- internal/test/cleanup.go
- internal/test/crdbuilder.go
- internal/test/envtest.go
Related issue https://github.com/rancher-sandbox/rancher-turtles/issues/30
This is the first PR for introducing a wrapper around the rancher cluster object to avoid fighting with dependencies. We can use `mapstucture` library that will convert from wrapper to unstructured and back based on JSON tags. The wrapper can be later extended with the status field for example.
I will introduce the actual usage of it in a follow-up PR.
Fixes #
**Checklist**:
> Add rancher cluster wrapper

- README.md
- config/manager/manager.yaml
- config/rbac/leader_election_role_binding.yaml
- scripts/kind-cluster-with-extramounts.yaml
kind/bug
This PR is a fix for:
- local environment setup, compatible versions between rancher and k8s
- leader election
- health check port
Logs are now showing no errors:
```
[event: pod rancher-turtles-system/rancher-turtles-controller-manager-68954b894c-hg4mt] Container image "rancher-sandbox/ghcr.io_rancher-sandbox_rancher-turtles:tilt-06db84abc2b1e90f" already present on machine
I0720 12:55:22.053458       1 request.go:601] Waited for 1.001781355s due to client-side throttling, not priority and fairness, request: GET:[https://10.96.0.1:443/apis/cluster.x-k8s.io/v1alpha3?timeout=32s](https://10.96.0.1/apis/cluster.x-k8s.io/v1alpha3?timeout=32s)
I0720 12:55:22.556030       1 listener.go:44] controller-runtime/metrics "msg"="Metrics server is …
```
> Fix startup leader election

- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
Requeue if rancher cluster name is empty, it may not be immediately after creation. 
Fixes #
**Checklist**:
> Requeue if rancher cluster name is empty

- .github/workflows/golangci-lint.yml
- .github/workflows/lint.yaml
- .golangci.yml
Adds more linters to .golangci.yml and bumps go to 1.20 in GH workflow files
Fixes #
**Checklist**:
> Add more linters to .golangci.yml

- .gitignore
- go.mod
- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
- internal/controllers/suite_test.go
- util/annotations/helpers.go
- util/annotations/helpers_test.go
- util/predicates/cluster_predicates.go
- util/predicates/cluster_predicates_test.go
kind/feature
This PR adds a support for deleting the CAPI cluster from Rancher, so that it is no longer listed in Rancher by introducing a 
`clusterImportedAnnotation`.  The cluster creation and deletion then as following:
- renames existing `importAnnotationName` to `importAnnotation` to align with new annotation
- introduces `util` folder where we have `annotations` and `predicates` packages 
- `reconcileDelete` made to receive two inputs: CAPI and Rancher cluster, and  if the Rancher Cluster has `ClusterImportedAnnotation` annotation, then we annotate the CAPI cluster to say don't auto-import again.
- introduces unit tests
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> ✨ Support deleting the cluster from Rancher

- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
- internal/controllers/suite_test.go
Use label instead of annotation for importing clusters, I also changed label key to `"cluster-api.cattle.io/rancher-auto-import"` so it's more similar to other rancher labels/annotations.
Fixes https://github.com/rancher-sandbox/rancher-turtles/issues/59
**Checklist**:
> Use label instead of annotation for importing clusters

- internal/controllers/import_controller.go
We set an annotation on cluster delete but we don't patch CAPI cluster so the change is reflected.
Fixes #
**Checklist**:
> Patch CAPI cluster after reconciling it

- Makefile
- tilt/project/Tiltfile
We bumped Go to 1.20.7 in #66 and this is causing pod `rancher-turtles-controller-manager` to fail when creating a new Tilt development environment. While we troubleshoot and identify the cause of the issue, we agreed to downgrade Go to 1.20.4 in:
- `Makefile`
- `tilt/project/Tiltfile`
This PR is a revert of #66 in these files.
Fixes #
**Checklist**:
> Revert: downgrade Go to 1.20.4

- go.mod
- go.sum
- internal/controllers/import_controller.go
kind/cleanup
Using CAPI utilyaml to collect and apply raw manifests from import endpoint.
- Improve logging
- Reduce number of remote cluster requests from 2 to 1 (Create)
Fixes #
**Checklist**:
> 🌱 Use utilyaml to collect agent manifests in remote cluster

- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
- util/naming/name_converter.go
- util/naming/name_converter_test.go
kind/bug
This addresses the problems described in #86.
**Checklist**:
> :bug: Allow rancher cluster to be deleted from UI

- CONTRIBUTING.md
- Makefile
- README.md
- docs/adr/0000-template.md
- docs/adr/0001-use-adrs.md
- docs/adr/0002-use-helm.md
- docs/adr/0003-deletion-strategy.md
- hack/generate-doctoc.sh
Adds `CONTRIBUTING.md` to the repo and doctoc script to be able to run the tool locally and via Makefile target. Also pass `docs/adr` to the doctor script and add changes after run. 
**Checklist**:
> 📖 Add CONTRIBUTING guide 

- docs/adr/0004-running-out-of-rancher-manager-cluster.md
Adds ADR for running Rancher Turtles out of Rancher Manager cluster.
Fixes #94 
**Checklist**:
> ADR: Running out of Rancher Manager cluster

- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
- main.go
This is intended to allow a Rancher operator to choose between deploying rancher-turtles in the same or a different cluster to Rancher Manager. The current implementation of rancher-turtles defaults to an in-cluster configuration with both Rancher Manager and rancher-turtles supposed to be installed together in the same cluster.
The initial idea is to create the client based on whether a flag with a path to a kubeconfig file is passed. When this parameter is used, rancher-turtles will load the REST Config from this file and create a client for an out-of-cluster installation. If it is not, it defaults to the current in-cluster behavior.
Issue #19 
**Checklist**:
> Support out-of-cluster installation

- internal/controllers/import_controller.go
- util/predicates/cluster_predicates.go
- util/predicates/cluster_predicates_test.go
- util/predicates/suite_test.go
- util/util.go
Add new predicates to filter out clusters that don't have a control plane ready or were not marked for import. I didn't remove all similar logic from reconciler because I've seen in the past predicates failing and unexpected behavior happening because of that. 
Fixes #
**Checklist**:
> Introduce new predicates

- .github/workflows/test_chart.yaml
- Makefile
- charts/rancher-turtles/Chart.lock
- charts/rancher-turtles/Chart.yaml
- charts/rancher-turtles/values.yaml
- test/e2e/e2e_suite_test.go
Add CAPI operator to helm chart dependency, I will also open a follow-up PR that creates core provider before Rancher turtles are installed.
.
Fixes https://github.com/rancher-sandbox/rancher-turtles/issues/91
**Checklist**:
> Add CAPI operator as a dependency to chart

- test/e2e/import_test.go
Using cluster proxy directly will eliminate the issue with cluster connectivity check on mac, as it uses fix for load balancer address described in https://cluster-api.sigs.k8s.io/clusterctl/developers#fix-kubeconfig-when-using-docker-desktop-and-clusterctl
Fixes #
**Checklist**:
> 🐛 Fix cluster connectivity check on mac

- .github/workflows/test_chart.yaml
- README.md
- charts/rancher-turtles/Chart.yaml
- charts/rancher-turtles/templates/core-provider.yaml
- charts/rancher-turtles/templates/kubeadm-bootstrap.yaml
- charts/rancher-turtles/templates/kubeadm-control-plane.yaml
- charts/rancher-turtles/values.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/helpers_test.go
- test/e2e/resources/config/capi-providers-secret.yaml
- test/e2e/resources/config/capi-providers.yaml
kind/feature
Add new values and template to helm chart so we can deploy CAPI with one command, assuming rancher and cert-manager are running users will be able to install extension, CAPI operator and CAPI like this:
```
helm repo add rancher-turtles https://rancher-sandbox.github.io/rancher-turtles
helm repo update
helm install rancher-turtles rancher-turtles/rancher-turtles --create-namespace -n rancher-turtles-system
```
Fixes https://github.com/rancher-sandbox/rancher-turtles/issues/18
Fixes https://github.com/rancher-sandbox/rancher-turtles/issues/105 …
> ✨ Install CAPI using operator after chart is installed

- internal/controllers/import_controller.go
This fixes a few bugs reported on the support for Rancher Turtles being installed outside of the Rancher Manager cluster, which includes not setting clients properly for the different scenarios #124.
Fixes #124 
**Checklist**:
> fix: use rancherClient in reconcileNormal for out of cluster support

- docs/adr/0000-template.md
This change disable the link checker for the ADR template file.
Fixes #
> chore: disable link checker for the template

- .golangci.yml
kind/cleanup
Adding per review comment https://github.com/rancher-sandbox/rancher-turtles/pull/84#pullrequestreview-1621728049
Fixes #
**Checklist**:
> 🌱 Add turtlesnaming to linter package

- test/e2e/helpers_test.go
- test/e2e/resources/testdata/fleet-capi-test.yaml
Point to upstream repo instead of forked one in e2e testing
@Danil-Grigorev I found this commit https://github.com/richardcase/fleet-clusters/compare/main...Danil-Grigorev:fleet-clusters:main on top of the https://github.com/rancher-sandbox/rancher-turtles-fleet-example repo commits. Does the latter need to be synced with your fork or can be dropped?
**Checklist**:
> 🌱 Use upstream repo instead of forked in e2e testing

- .github/workflows/release.yaml
- Makefile
kind/feature
This PR extends existing release functionality for publishing rancher-turtles image with a set of steps required to publish the image into prime registry.
For helm charts publishing, the old location would still be used.
Fixes #81 
**Checklist**:
> ✨ Push to prime registry on release workflow run

- .github/workflows/nightly-chart-and-image-publish.yaml
Adds nightly rancher turtles chart and docker image publishing GitHub workflow which runs every day to ghcr.io 
Part of: https://github.com/rancher-sandbox/rancher-turtles/issues/117
**Checklist**:
> ✨ Add nightly chart and image publish GH workflow

- .github/workflows/e2e-long.yaml
- .github/workflows/e2e-short.yaml
- Makefile
- test/e2e/config/operator.yaml
- test/e2e/data/capi-operator/capi-providers-secret.yaml
- test/e2e/data/capi-operator/full-providers.yaml
- test/e2e/data/capi-operator/full-variables.yaml
- test/e2e/data/cluster-templates/aws-eks-mmp.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/helpers_test.go
- test/e2e/import_gitops.go
- test/e2e/import_gitops_test.go
Added a new test that will use the AWS provider. It will provision a EKS based cluster using managed node group.
Also labels have been added to the tests so that the tests can be filtered with the `--test-filter` flag when running them. This is to allow short and full tests. There are 2 constants `short` and `full` thatcan be included on the test declarations.
Fixes #92 
**Checklist**:
> feat: add CAPA e2e test

- README.md
- charts/rancher-turtles/templates/core-provider.yaml
- charts/rancher-turtles/templates/kubeadm-bootstrap.yaml
- charts/rancher-turtles/templates/kubeadm-control-plane.yaml
- charts/rancher-turtles/values.yaml
This PR updates the chart so that  when it deploys the CoreProvider it also sets the environment variables for the features:
- CRS
- Topology
These features are currently set by [manually creating a secret](https://docs.rancher-turtles.com/docs/getting-started/install_turtles_operator) with the desired values for the environment variables `CLUSTER_TOPOLOGY` and `EXP_CLUSTER_RESOURCE_SET`. This secret will now be created as part of the chart installation and both features will default to `true`. These can otherwise be disabled passing the parameters to Helm:
`--set cluster-api-operator.cluster-api.secretConfig.name="user-secret-name"`
`--set cluster-api-operator.cluster-api.secretConfig.namespace="user-secret-namespace`
When both these parameters are …
> feat: update chart to enable crs and topology features

- Makefile
The full e2e test run was failing due to double escaping the label filter which caused the filter to be interpretated as a command. This change remove the quote from the filter variable value.
Fixes #149 
**Checklist**:
> fix: full e2e test failure

- .github/dependabot.yaml
Dependabot is bumping `ginkgo` in https://github.com/rancher-sandbox/rancher-turtles/pull/141 but it's only checking the main Go modules in `./`. This is not updating modules in `./test` and is causing CI failures.
This is equivalent to what's used in [cluster-api](https://github.com/kubernetes-sigs/cluster-api/blob/main/.github/dependabot.yaml).
Fixes #154 
**Checklist**:
> 🌱 chore: add dependabot go.mod check on ./test

- .github/workflows/release.yaml
This PR changes the following in the release workflow:
- Updates release name, which is now prefixed by the name of the project, to only use the semver format as in `v0.0.0-rc0`.
- Sets the release as draft.
- Includes the release changelog.
Fixes #171 
There are a couple of things that are not exactly what I expected:
- `chart-releaser` provides a `--make-release-latest` flag that does not seem to work. The `cr upload` command is passing it as false but it keeps setting the flag to the release. To fix this, after creating the release it updates it to draft …
> chore: change release name and generate release notes

- .github/workflows/release.yaml
- Makefile
- scripts/image-digest.sh
This PR adds SLSA signing and provenance to release:
- We publish an image for each arch we support and one multiarch, PR includes a script with a new make task that outputs all images and digests, these are later used to build a matrix for signing and verifying images: ```[{image: "image1:tag" digest: "imagedigest1"}, {image: "image2:tag" digest: "imagedigest2"}]```
- Sign artifacts with cosign and create provenance using a reusable workflow provided by `slsa-framework`
Fixes #
**Checklist**:
> Add SLSA signing and provenance to release

- .github/workflows/test_chart.yaml
- charts/rancher-turtles/templates/pre-install-job.yaml
- charts/rancher-turtles/values.yaml
Currently, installing Rancher Turtles in an existing Rancher Manager after disabling embedded CAPI, results in validating/mutating webhooks being left behind after the feature is disabled. If you try and apply a CAPI manifest you will get an error:
```
time="2023-10-03T14:18:36Z" level=error msg="error syncing 'cluster-fleet-local-local-1a3d67d0a899/clusters-clusters': handler bundle-deploy: failed to create  │
│ resource: Internal error occurred: failed calling webhook \"default.cluster.cluster.x-k8s.io\": failed to call webhook: Post \"https://capi-webhook-service.cat/ │
│ tle-provisioning-capi-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s\": service \"capi-webhook-service\" not found, requeuing"
```
To avoid having to …
> fix: use pre-install helm hook to prepare rancher for turtles

- .github/workflows/release.yaml
The current release workflow builds and publishes images to both GHCR and Prime registry. While creating the first Rancher Turtles release candidate we thought we could split these actions into different jobs for each registry.
- Building and publishing images in parallel reduces workflow time.
- Easier to troubleshoot independently when failure occurs.
This change also narrows the scope of environment variables to the specific jobs.
Fixes #169 
**Checklist**:
> 🌱 chore: differentiate ghcr and prod registry workflows

- main.go
kind/bug
When the rancher-turtles is installed in the cluster, but the rancher CRDs are not yet available, eventually the pod fails. Multiple restarts lead to CrashLoopBackOff, requiring a manual pod restart once rancher CRDs are installed and available in the cluster.
This *effectively* disables the cache setup timeout for resource discovery.
Fixes #180 
**Checklist**:
> :bug: Disable cache timeout on discovery for delayed rancher deployment

- .github/workflows/release.yaml
[chart-releaser](https://github.com/helm/chart-releaser) was setting new releases (created from GitHub Actions) as latest even though the flag `make-release-latest` was set to `false`. Apparently this was caused by the bool value not being parsed properly due to the way it was passed in the command. This very small change seems to be the proper way to do it.
With this edit, the `gh-cli` extra step to fix this at the end of the release process is no longer needed.
Fixes #
**Checklist**:
> chore: edit cr command to not set release as latest

- .github/workflows/e2e-long.yaml
Before this PR failures were reported for nightly runs only, now we will be notified every time tests fail.
Fixes #
**Checklist**:
> Always report e2e failures to slack

- test/e2e/suites/embedded-capi-disabled/embedded_capi_disabled_test.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
- test/testenv/rancher.go
With #190 we are changing the tests so that Rancher is installed first with the "embedded CAPI" feature flag enabled and then disabling it before installing Rancher Turtles. This PR adds a new E2E test scenario that covers the installation in reversed order: we install Rancher first with `embedded-cluster-api` disabled and then install Rancher Turtles.
Fixes #193 
QA reported https://github.com/rancher/rancher/issues/41724 a few months ago, describing a problem encountered when installing Rancher with the embedded CAPI feature flag set to false. After some investigation (mainly trial & error), it looks like using the format `--set features=embedded-cluster-api=false` does not …
> test: add e2e for rancher with embedded capi disabled

- .github/workflows/release.yaml
Remove environment variable for registry endpoint in prod-sign.
Fixes #
**Checklist**:
- [c] squashed commits into logical changes
> chore: use hardcoded registry endpoint for prod-sign

- .github/workflows/release.yaml
- scripts/image-digest.sh
GitHub detects outputs containing substrings that are part of secrets as insecure and blocks us from sharing them with downstream jobs. This is a proposal to fix this issue by double encoding outputs so that they are obfuscated. Then, these outputs are decoded in the signing/provenance jobs.
These outputs are not actually sensitive data but just the image location and, worst case scenario (user decodes the string output), this data is public anyway.
Fixes #211 
**Checklist**:
> chore: encode gh actions outputs

- .github/workflows/e2e-long.yaml
- .github/workflows/janitor.yaml
This adds the Azure janitor to the nightly e2e and as a separate periodic.
Fixes #
**Checklist**:
> chore: add azure janitor in dry-run

- .github/workflows/release.yaml
This PR removes the SLSA provenance jobs in the release workflow for both `ghcr` and `prod` registries. These jobs will be separated into a different workflow soon.
Fixes #230
**Checklist**:
> chore: disable slsa provenance in release workflow

- internal/controllers/import_controller.go
- util/predicates/cluster_predicates.go
Whilst testing ClusterClass it was noticed that the status.controlplaneready field isn't being set to true. However, the condition isn't being set to true.
This change will check both the status field and the condition. If either are true then we will reconcile the CAPI cluster.
Fixes #234 
**Checklist**:
> fix: check condition for controlplane ready

- .github/workflows/release-workflow.yml
- .github/workflows/release.yaml
- .github/workflows/release_build/action.yaml
- .github/workflows/release_sign/action.yaml
> Refactor release workflow to be reusable

- .github/workflows/e2e-long.yaml
~~While we work on having a reliable periodic e2e test environment, this is a proposal to run the tests in isolated mode. Currently, nightly tests are not providing useful information and this would at least add limited validation in our current state. We'll be missing the cloud scenarios but at least have a meaningful validation of the logic.~~
Nightly E2E tests are disables until the test environment is stable and output messages are relevant.
- Current nightly E2E tests are disabled.
- ~~The short variant of the E2E tests is executed nightly and on push to main, temporarily.~~
**Checklist**:
> chore: temporarily disable nightly e2e

- .github/workflows/nightly-test-release.yaml
Based on @Danil-Grigorev's work on refactoring the release process to make jobs reusable [here](https://github.com/rancher-sandbox/rancher-turtles/pull/232), this PR adds a nightly workflow (frequency can be modified if nightly is considered too often) that validates these reusable workflows by following the release process and avoiding pushing images to the production registry and publishing helm charts.
The testing workflow is based on creating a fake tag `t9.9.9-fake` (this naming is used to avoid triggering the real release action and is similar to the approach used in [upstream CAPI](https://github.com/kubernetes-sigs/cluster-api/blob/45d39d6b0bd61fd1ada3c3bc57664de5d8ad25e0/.github/workflows/weekly-test-release.yaml#L28)). The workflow then …
> 🌱  Run release workflow periodically

- .github/workflows/nightly-test-release.yaml
The first few executions of the nightly release test are cancelled after one of the re-used workflows fails which causes a cancelled status and not a failure. The notification job in the workflow is only configured to run if `failure()` and this PR adds the `cancelled()` state to the condition to get notified when this occurs.
Fixes #269 
**Checklist**:
> chore: send alarm message when release test is cancelled

- .github/workflows/release-workflow.yml
The recently introduced nightly test release is not failing when signing the image. @Danil-Grigorev identified the cause of error as this workflow is not triggered by a new tag but periodically and hence the checkout during signing was referencing `refs/remotes/origin/main` and not the testing tag `refs/tags/v9.9.9-fake`.
This PR adds an explicit `ref` key to the checkout steps in `build` and `sign`. This should force the periodic workflow to use the proper tag and should not alter the behavior when creating an actual release.
Fixes #272 
**Checklist**:
> fix: nightly release test failing to sign images

- test/e2e/data/capi-operator/full-providers.yaml
This change pins the CAPZ version to v1.11.5 for E2E tests. A new issue has been created to track why latest version is not provisioning AKS clusters #281.
Fixes #198 
**Checklist**:
> fix: pin capz versions in e2e tests

- charts/rancher-turtles/templates/_helpers.tpl
- charts/rancher-turtles/templates/pre-install-job.yaml
kind/bug
currently the postinstall jobs `rancher-mutatingwebhook-cleanup` and `rancher-validatingwebhook-cleanup` fail.
The rancher/kubectl images only have the "normal" kubernetes version, the extra part for rke2/k3s extension has to be removed
v1.26.8+rke2r1 has to formatted to v1.26.8
Fixes #280 
**Checklist**:
> fix: #280 strip kubernetes version

- .github/workflows/release-workflow.yml
The changes introduced with #273 have not solved the issue of the nightly test release workflow verifying the signed images with `cosign`. After some investigation together with @Danil-Grigorev, the error in the verification seems to be related to the way the action authenticates against cosign for signing. It populates a subject in the signing data that is based on the ref/email (refer to [this](https://github.com/sigstore/cosign#sign-a-container-and-store-the-signature-in-the-registry)):
- If the release is triggered by a tag creation (our release procedure), the subject will be, for example, `https://github.com/rancher-sandbox/rancher-turtles/.github/workflows/release-workflow.yml@refs/tags/v0.0.0` which must match the `--certificate-identity` …
> fix: cosign verify for release test workflow

- .github/workflows/e2e-long-test.yaml
A new workflow to test the e2e on self-hosted runners.
Fixes #
**Checklist**:
> test: test the e2e using a self-hosted runner

- .github/workflows/e2e-long-test.yaml
- .github/workflows/e2e-short-test.yaml
- Makefile
Small change to allow you to run a specific suite when running tests and splits up the self-hosted runner test into a step per e2e suite.
Fixes #
**Checklist**:
> test: allow limiting which suites are run

- test/e2e/suites/import-gitops/import_gitops_test.go
Due to an issue with CAPZ lets disable the CAPZ test and re-enable the CAPA test.
NOTE: we will enable the azure janitor in the future
Fixes #
**Checklist**:
> test: disable the Azure test and re-enable the AWS test

- test/e2e/data/capi-operator/capa-variables.yaml
- test/e2e/data/capi-operator/capz-identity-secret.yaml
- test/e2e/data/capi-operator/full-providers.yaml
kind/bug 
Secrets are created before the providers, so the namespaces should be created together in an e2e test run.
Fixes #
**Checklist**:
> 🐛 Variable secrets should be created in existing namespaces

- charts/rancher-turtles/templates/_helpers.tpl
There is an issue installing Rancher Turtles on EKS using the chart as the kubernetes version in EKS doesn't follow semver. For example, EKS will return a version like `v1.26.12-eks-5e0fdde` and this means that we then try and pull the `docker.io/rancher/kubectl:v1.26.12-eks-5e0fdde` image when performing the cleanup tasks.
The function to strip the suffix from the kubernetes version has been updated to handle EKS, AKS and GKE.
Fixes #347 
**Checklist**:
> fix: installation on eks

- charts/rancher-turtles/templates/_helpers.tpl
There is an issue installing Rancher Turtles on EKS using the chart as the kubernetes version in EKS doesn't follow semver. For example, EKS will return a version like `v1.26.12-eks-5e0fdde` and this means that we then try and pull the `docker.io/rancher/kubectl:v1.26.12-eks-5e0fdde` image when performing the cleanup tasks.
The function to strip the suffix from the kubernetes version has been updated to handle EKS, AKS and GKE.
Relates #347
This is a cherry-pick from main.
**Checklist**:
> [Release 0.4] fix: installation on eks

- docs/adr/0008-managementv3-clusters-support.md
This ADR is a proposal on how support for `management.cattle.io/v3` clusters is implemented, based on investigation during the development process. 
**The main point of concern here is how we manage cluster naming**. Since `management.cattle.io/v3` clusters are required to have a name that satisfies the string `c-` followed by exactly five characters, we cannot use the display name (the one that appears in Rancher dashboard) as we do with `provisioning.cattle.io/v1` clusters (where name and display name are the same).
Creating a randomized 5-character suffix presents the challenge of not being able to track the resource while reconciling like we do in the existing `provisioning.cattle.io/v1` import controller, since we fetch the cluster on `Name` …
> docs: managementv3 cluster support strategy

- test/e2e/data/capi-operator/capi-providers.yaml
This prevents us from having a test environment with mismatched capi core and capd versions.
Fixes #
**Checklist**:
> chore: e2e environment with fixed capd version

- .github/dependabot.yaml
With this change we will get dependency bump early (which can be just a notification in case of incompatible changes), including CAPI version and CAPI Operator version for CAPIProvider implementation.
Fixes #384 
**Checklist**:
> 👾 Add dependabot rule to bump CAPI Operator dependency as early as possible

- api/v1alpha1/capiprovider_types.go
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
- internal/sync/secret_mapper_sync.go
- internal/sync/secret_mapper_sync_test.go
Implementing a separate field for a fully qualified `namespace:name` reference to the rancher cloud credentials secret, as an alternative to the name annotation.
Fixes #386 
**Checklist**:
> 🪴 Rancher credentials lookup by namespace name

- .github/dependabot.yaml
Apparently dependabot does not support separation of groups for the same dependency engine (gomod). 
https://github.com/rancher-sandbox/rancher-turtles/runs/21812211327
`The property '#/updates/1' is a duplicate. Update configs must have a unique combination of 'package-ecosystem', 'directory', and 'target-branch'`
The problem appears to be due to: https://github.com/dependabot/dependabot-core/issues/1778
To still benefit from early CAPI Operator version bump, changing interval to daily.
> :bug: Fix dependabot duplicate rule issue

- api/v1alpha1/conditions_consts.go
- charts/rancher-turtles/Chart.yaml
- internal/sync/provider_sync.go
- internal/sync/provider_sync_test.go
- test/e2e/config/operator.yaml
This implementation adds `LastAppliedConfigurationTime` to `CAPIProvider` conditions, to reflect last update time for the infrastructure. To make it work, when the condition is outdated (more then 5 minutes old), then the `operator.cluster.x-k8s.io/applied-spec-hash` annotation on the provisioned CAPI Operator resource gets updated to empty value. This causes CAPI Operator to validate and update the provisioned infrastructure objects in case of a difference with repository content.
Fixes #348 
**Checklist**:
<!-- Put an "X" character inside the brackets of …
> ✨ Re-apply capi infra periodically

- Makefile
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/clusterctl-config.yaml
- charts/rancher-turtles/values.yaml
- test/e2e/config/operator.yaml
- test/e2e/const.go
- test/e2e/data/capi-operator/capi-providers.yaml
Helm chart installs a config map with a list of provider versions to use. This is mounted in a known location for the CAPI Operator deployment, allowing for the clusterctl to pick these values as default provided. 
If no version is explicitly specified while creating a provider, then the version deployed will always be consistent with the version in the ConfigMap.
Fixes #401 
**Checklist**:
> ✨ Pin installed versions for CAPI Operator

- .github/workflows/janitor.yaml
Enable `aws-janitor` to clean resources using a mark and delete approach (first execution mark/next delete), including:
- EKS clusters.
- Auto Scaling Groups.
- Load Balancers.
- Security Groups.
- CloudFormation stacks.
**Resources that include the tag `janitor-ignore` will be skipped.**
Fixes #368 
This PR is waiting on an initial release of https://github.com/rancher-sandbox/aws-janitor, which will be created after https://github.com/rancher-sandbox/aws-janitor/pull/4.
`aws-janitor` runs after `azure-janitor`. It will run even if the previous job fails and it'll be skipped only if the action is cancelled.
**Checklist**:
> :seedling: chore: configure janitor to cleanup aws resources

- api/v1alpha1/capiprovider_wrapper.go
- internal/controllers/capiprovider_controller.go
- internal/controllers/capiprovider_controller_test.go
- internal/controllers/import_controller_test.go
- internal/controllers/import_controller_v3.go
- internal/sync/core.go
- internal/sync/interface.go
- internal/sync/interface_test.go
- internal/sync/provider_sync.go
- internal/sync/provider_sync_test.go
- internal/sync/secret_mapper_sync.go
- internal/sync/secret_sync.go
- test/e2e/specs/import_gitops.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/suites/update-labels/update_labels_test.go
- test/e2e/suites/v2prov/v2prov_test.go
Add integration tests for CAPI Provider reconcile process, focused on field modification.
Due to use of server-side apply, we are seeing some frequent conflicts on the resource apply, when it comes to `v1.Secret` resources. Unfortunately it is unavoidable when using `stringData` field actively, what we have to do for rancher creds sync. It is mentioned in k/k [docs](https://kubernetes.io/docs/tasks/configmap-secret/managing-secret-using-config-file/#specify-unencoded-data-when-creating-a-secret), so manual deduplication logic was added for secret operations.
Fixes #381 
Depends on #395, #397 …
> 🌱 Add tests for capi provider edit operations

- test/e2e/config/operator.yaml
Looks like the interval `wait-delete-cluster` used when cleaning up the E2E test environment is missing. If it takes longer to remove the cluster, this causes it to time out.
Fixes #
**Checklist**:
> :seedling: test: add wait-delete-cluster interval

- .github/workflows/nightly-test-release.yaml
- .github/workflows/release.yaml
Release workflow is failing after the move to Go 1.22. This PR explicitly configures the action to run the new Go version.
Fixes #
**Checklist**:
> 🌱 chore: update go version in release test workflow

- internal/controllers/capiprovider_controller_test.go
- internal/controllers/patch_kcfg_controller_test.go
- internal/sync/provider_sync.go
- internal/sync/provider_sync_test.go
- internal/sync/secret_mapper_sync_test.go
- main.go
Add logic for conditions merge on CAPIProvider resource. This fixes situation when a LastAppliedConfigurationTime is set, but is overwritten by the child CAPI Operator conditions, causing forced cleanup of annotation and infinite reconciles.
Additionally, cache re-sync time reduced to 2 minutes so that the infrastructure is re-applied periodically.
Fixes #407 
Depends on #396 
**Checklist**:
> :bug: Provider re apply tests

- .github/workflows/ci.yaml
- .github/workflows/codeql.yml
- .github/workflows/dependabot.yml
- .github/workflows/e2e-short.yaml
- .github/workflows/golangci-lint.yml
- .github/workflows/lint.yaml
- .github/workflows/pr-md-link-check.yaml
- .github/workflows/pr_size_labeler.yml
- .github/workflows/pr_type.yaml
- .github/workflows/test_chart.yaml
- .github/workflows/trivy.yml
This is a followup on #408, bumping used go version to 1.22, and updating event handlers on all required jobs to always run on dependabot PRs when a push occurs. This is needed to mitigate the issue when the last commit does not trigger changes - https://github.com/orgs/community/discussions/62346
Fixes #
**Checklist**:
> 🌱 Bump go version in dependabot workflow 

- .github/workflows/release-workflow.yml
[Nightly test release](https://github.com/rancher/turtles/actions/runs/8417796108) GH action is failing while[ signing image with cosign](https://github.com/rancher/turtles/actions/runs/8417796108/job/23047003714#step:3:293) since the  
`--certificate-identity` points to `rancher/rancher-turtles` instead of `rancher/turtles` after recent repo move and this PR tries to fix that.
Fixes #
**Checklist**:
> 🐛 Fix repo name in release-workflow.yml GH workflow

- .github/workflows/run-e2e-suite.yaml
A [recent run](https://github.com/rancher/turtles/actions/runs/8436973843) of the e2e tests failed because the aws-iam-authenticator wasn't installed.  This change adds installation to the workflow.
Fixes #
**Checklist**:
> fix: install aws-iam-authenticator

- docs/adr/0009-publish-chart-to-rancher-charts.md
This ADR puts together details of the two main options for serving Helm charts:
- [rancher/charts](github.com/rancher/charts).
- Custom Turtles repository.
The idea is that we go over the pros/cons as a team and try to decide which is the best option and define an action plan, if necessary.
Fixes #
**Checklist**:
> :book: docs: add helm chart repository adr

- charts/rancher-turtles/Chart.yaml
This introduces recent fixes for provider upgrades.
Fixes #
**Checklist**:
> 🌱 Bump operator dependency to 0.9.1

- .github/workflows/release-workflow.yml
- .github/workflows/release_sign/action.yaml
Nightly release [jobs](https://github.com/rancher/turtles/actions/runs/8515988902) failing due to the [bug](https://github.com/slsa-framework/slsa-github-generator/issues/1163) in the version of slsa-GH generator used (v1.9.0) and this patch updates it to new version: v1.10.0
Fixes #
**Checklist**:
> Fix nightly release CI job

- test/testenv/eksctl_provider.go
This change adds tags to the resources created by eksctl for the following reasons:
- identify which team owns the resources
- aid automatic clean-up of the resources
Fixes #
**Checklist**:
> chore: add tags to eks resources

- .github/workflows/test_chart.yaml
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/post-delete-job.yaml
- charts/rancher-turtles/templates/rke2-bootstrap.yaml
- charts/rancher-turtles/templates/rke2-controlplane.yaml
- charts/rancher-turtles/values.yaml
- test/testenv/turtles.go
> Install RKE2 by default

- CONTRIBUTING.md
- README.md
- charts/rancher-turtles/README.md
- charts/rancher-turtles/app-readme.md
Documentation is now available at turtles.docs.rancher.com and this PR updates any references to the old URL.
Fixes #
**This is waiting for https://github.com/rancher/turtles-docs/pull/70 to be merged**, when the new site will become available and the old one deprecated.
**Checklist**:
> :seedling: chore: update references to documentation site

- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/deployment.yaml
- charts/rancher-turtles/values.yaml
- feature/feature.go
- internal/controllers/import_controller.go
- internal/controllers/import_controller_v3.go
This change adds an experimental feature that when enabled will copy the labels from the CAPI Cluster to the created Rancher Cluster resource.
By copying the labels it allows "cluster groups" to be easily used to automatically deploy applications to CAPI created clusters.
Fixes #461 
**Checklist**:
> feat: add label propagation

- internal/controllers/capiprovider_controller.go
- internal/controllers/capiprovider_controller_test.go
- internal/controllers/import_controller_test.go
- internal/sync/provider_sync_test.go
- internal/sync/secret_mapper_sync.go
- internal/sync/secret_mapper_sync_test.go
We are not patching status with credentials updated condition in situations when the rancher secret fetch fails.
Adding some tests and updating existing to cover these scenarios.
Fixes #
**Checklist**:
> 🌱 Ensure controller always patches CAPIProvider status

- test/e2e/specs/import_gitops.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/suites/import-gitops/import_gitops_test.go
- test/e2e/suites/managementv3/managementv3_test.go
This change adds a re-import check after running the existing `import_gitops` suite. The validation sits behind a condition passed as input `TestClusterReimport` which is proposed to only be enabled on CAPD tests to limit the effect on running time, which is already considerably long. This is also the reason why the new re-import validation is added to an existing test suite and not as a new one.
Both controller types are supported for now (v1 and v3 clusters) until we move completely to only v3.
To simplify and reduce code duplication, the validation on the Rancher cluster resource is now part of a `validateRancherCluster` function which is called during the "normal" test and then again after re-import.
The process of re-import is as follows:
- …
> :seedling: cover cluster reimport after running e2e

- test/e2e/const.go
- test/e2e/data/chartmuseum/deployment.yaml
- test/e2e/suites/import-gitops/suite_test.go
- test/framework/chartmuseum_helper.go
- test/testenv/charmuseum.go
- test/testenv/turtles.go
Run helm chart upgrade from GA version test in CI as a pre-submit job.
Fixes #486
**Checklist**:
> 🌱 Perform helm chart upgrade tests in pre-submits

- Makefile
- test/e2e/config/operator.yaml
- test/e2e/suites/import-gitops/suite_test.go
- test/testenv/turtles.go
After running the `import-gitops` test suite, we verify that `helm uninstall` works on Turtles. This also upgrades Helm to `v3.14.0`, as `v3.8.1` was failing to detect the `--cascade` flag.
Fixes #410 
The uninstall of Turtles may fail unexpectedly due to a problem with the CAPI Operator Helm chart and CRDs being deleted in such a way that doesn't guarantee the order and may end up in a deadlock caused by a finalizer that is never removed.
**Note**: perhaps we should wait to have this sorted out before merging this change and having the uninstall step as part of the E2E tests.
**Checklist**:
> :seedling: chore: cover uninstall in e2e tests

- .gitignore
- charts/rancher-turtles/Chart.yaml
This PR implements a missing dependencies in the Chart file; the values.yaml implements a boolean field called `cluster-api-operator` that will instruct helm to install or not install the CAPI Operator. 
**Checklist**:
None needed.
> [Bug] fix missing conditional for CAPI Operator dependencies

- .github/workflows/dependabot.yml
Dependabot CI checks are failing on some PRs after replacing the no longer supported action with manual steps [example](https://github.com/rancher/turtles/actions/runs/9249544453/job/25447774389). Looks like this is because the Action we were using sets a default `git add .` [here](https://github.com/EndBug/add-and-commit?tab=readme-ov-file#inputs) and it is missing now, so the commit returns error code 1 when there are no changes to commit. This PR simply adds a `git add .` which hopefully is enough to mimic the removed action's behavior.
Fixes #
**Checklist**:
> fix: git add files in dependabot workflow

- api/v1alpha1/capiprovider_types.go
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- charts/rancher-turtles/templates/clusterctl-config.yaml
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- charts/rancher-turtles/values.yaml
- config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
- test/e2e/suites/import-gitops/suite_test.go
This change introduces CAAPF as experimental feature in turtles, bringing automatic Fleet cluster management per CAPI cluster, and tight ClusterClass integration with ClusterGroups.
Fixes #
**Checklist**:
> Enable addon provider fleet as experimental

- .github/workflows/e2e-short.yaml
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/post-upgrade-job.yaml
- charts/rancher-turtles/values.yaml
- test/e2e/specs/migrate_gitops_provv2_mgmtv3.go
- test/e2e/suites/import-gitops/import_gitops_test.go
Perform automatic provisioning cluster removal on upgrade with `v3 clusters` feature flag enabled.
In case of a duplicate cluster entries, a user can re-run the upgrade without settings change.
Fixes #
**Checklist**:
> 🌱 Cleanup v1 cluster before creating v3 clusters on upgrade

- scripts/import-controller-migration.sh
kind/feature
Migrating to the new import controller based on `clusters.management.cattle.io` (v3 clusters) means we need to apply changes to the existing Rancher cluster resources to let the new controller identify CAPI clusters as already imported. As described in the migration proposal #573, the v3 controller looks for cluster resources marked with the following labels:
```bash
cluster-api.cattle.io/capi-cluster-owner
cluster-api.cattle.io/capi-cluster-owner-ns
cluster-api.cattle.io/owned
```
`cluster-api.cattle.io/owned` is added to all clusters imported via Turtles, even if using the existing `clusters.provisioning.cattle.io` (v1 clusters) based controller. The other two labels must be added to the existing `clusters.management.cattle.io` …
> feat: add script for import controller migration

- test/e2e/suites/import-gitops/import_gitops_test.go
- test/e2e/suites/migrate-gitops/migrate_gitops_provv1_mgmtv3_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
Due to migration suite running together with import tests, the chart state in the same bootstrap cluster was modified from one test to another. This was causing e2e flakes, and this change should fix it.
Fixes #
**Checklist**:
> 🐛 Separate auto-migration e2e from the import tests

- Tiltfile
- internal/controllers/helpers.go
- internal/controllers/import_controller_v3.go
- internal/controllers/import_controller_v3_test.go
This PR allows migrating from V1->V3 cluster without reimporting the clusters. Rancher already creates a V3 cluster for every V1 cluster. V3 cluster controller will check that V1 cluster includes a migrated annotation or exists at all for a given v3 cluster if the annotation is present, the reconciliation will continue as expected.
Users are required to set proper labels on the existing V3 cluster before migrating, this will be described in the ADR and rancher turtles docs.
Fixes #
**Checklist**:
> Add v1->v3 cluster migration

- test/e2e/suites/embedded-capi-disabled/embedded_capi_disabled_test.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
`embedded-capi-disabled` E2E test suite has been failing for a few days now. As the default installation of Turtles is now using the v3 controller, we need to explicitly install Turtles with v1 controller to run the existing validation.
Fixes #592 
**Checklist**:
> test: fix v1 controller test on embedded-capi-disabled suite

- internal/controllers/import_controller_v3.go
- internal/controllers/import_controller_v3_test.go
As we are unable to set ownership references from CAPI cluster to a cluster scoped management v3 cluster, we have to manage deletion manually. This comes with a problem of tracking deletion order for rancher/capi cluster, and setting `imported` annotation to prevent re-import scenario.
There is a race condition if removal of management v3 cluster happens too fast - turtles misses the opportunity to set `imported` annotation first and causes immediate re-import of the cluster. To prevent such scenario, we need to set `capicluster.turtles.cattle.io` to the management v3 resource we created at all times, and clean it up within the `imported` annotation handling scope on deletion.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, …
> 🐛 Apply finalizer on rancher cluster to avoid re-create race condition

- test/e2e/data/capi-operator/capi-providers.yaml
- test/e2e/suites/embedded-capi-disabled-v3/embedded_capi_disabled_v3_test.go
- test/e2e/suites/embedded-capi-disabled-v3/suite_test.go
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/import_gitops_test.go
Structure E2E in differentiated suites for v3 checks, including adding validations for `embedded-capi-disabled` which so far only has v1 test coverage.
Additionally, this disables tests involving CAPRKE2 + CAPD until we bump CAPI version.
Fixes #477
**Checklist**:
> test: restructure e2e v1v3 suites

- .github/workflows/e2e-long.yaml
This change adds v3 suites to nightly E2E execution.
Additionally, `embedded-capi-disabled` suite has been failing for a few days but the alert we receive in Slack is marking `update-labels` as root of the issue. This fixes the naming in the E2E workflow definition.
Fixes #
**Checklist**:
> chore: add v3 checks to nightly + fix e2e naming in workflow yaml

- charts/rancher-turtles/templates/post-upgrade-job.yaml
- internal/controllers/import_controller.go
- internal/controllers/import_controller_test.go
- internal/controllers/import_controller_v3.go
- main.go
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/testenv/turtles.go
Add downgrade procedure as described in the ADR #579 
Fixes #
**Checklist**:
> 🌱 Support for management v3 downgrade to provisioning v1 with automigration

- Makefile
- test/e2e/const.go
- test/e2e/data/cluster-templates/vsphere-kubeadm.yaml
- test/e2e/data/gitea/ingress.yaml
- test/e2e/flags.go
- test/e2e/helpers.go
- test/e2e/specs/import_gitops.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/framework/helper.go
- test/framework/kube_helper.go
- test/framework/rancher_helpers.go
- test/testenv/gitea.go
This PR adds an option to set up a custom ingress object for Gitea. We need an ingress for every service we want to expose to the local host on Mac. 
Setting up Gitea ingress is enabled by setting an e2e flag, we'll rethink this approach along with other flags as a part of https://github.com/rancher/turtles/issues/603.
Fixes #
**Checklist**:
> E2E: Add custom ingress for gitea

- docs/release.md
When a new release is available, we need to notify a list of Slack channels. This step is now added to the release guide.
Fixes #
**Checklist**:
> docs: add notification step to release guide

- charts/rancher-turtles/templates/addon-provider-fleet.yaml
This change ensures that `CAAPF` is always installed/upgraded with existing `FleetAddonConfig` resource, which includes all required settings and label selectors for the turtles import expectations.
Fixes #605 
**Checklist**:
> ✨Add fleet addon config with auto-import label setting

- test/e2e/config/operator.yaml
- test/e2e/const.go
- test/e2e/data/cluster-templates/vsphere-rke2.yaml
- test/e2e/specs/import_gitops.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
- test/e2e/suites/import-gitops/import_gitops_test.go
- test/framework/git_helper.go
> Add RKE2 vSphere case to E2E suite

- internal/controllers/import_controller.go
- internal/controllers/import_controller_v3.go
- main.go
Due to deletion logic executed only based on CAPICluster state, the cleanup procedure never removes finalizer if it fails, and the CAPI cluster is annotated with “imported: true”. This needs to be executed separately, this PR changes that.
Typically the problem appeared after longer duration of time - once the cluster got fully imported and stayed untouched for a couple of minuted, then deleted. Thus [e2e](https://github.com/rancher/rancher-turtles-e2e) suite was more successful in uncovering the issue.
Fixes #589 
**Checklist**:
> Perform finalizer removal independently from main controller loop

- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- charts/rancher-turtles/templates/clusterctl-config.yaml
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/testenv/turtles.go
Pinned CAAPF to version 0.3.0 and marked it as non-experimental.
Since fleet released v0.10.1-rc.1, but it is not a part of rancher/charts yet, this PR can’t add full e2e suite, which will convert `CNI` installation to the cluster using fleet and enable `hostNetwork: true` setting.
Fixes #615  
**Checklist**:
> Pin CAAPF version to v0.3.0

- charts/rancher-turtles/Chart.yaml
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
- exp/etcdrestore/go.mod
- exp/etcdrestore/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Bump CAPI Operator to latest operator [v0.12 release](https://github.com/kubernetes-sigs/cluster-api-operator/releases/tag/v0.12.0)
Fixes #
**Checklist**:
> Bump CAPI Operator to v0.12.0

- test/e2e/const.go
- test/e2e/suites/embedded-capi-disabled-v3/suite_test.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/e2e/suites/update-labels/suite_test.go
- test/e2e/suites/v2prov/suite_test.go
- test/testenv/bootstrapclusterproviders.go
- test/testenv/rancher.go
- test/testenv/setupcluster.go
Part of https://github.com/rancher/turtles/issues/603. This PR makes bootstrap cluster setup and ingress deployment more flexible, if anyone imports our framework they can now inject their own way to create bootstrap cluster or deploy ingress on it.
Fixes #
**Checklist**:
> Refactor e2e suite setup to make it more customizable

- Makefile
- charts/rancher-turtles/templates/clusterctl-config.yaml
- exp/etcdrestore/go.mod
- exp/etcdrestore/go.sum
- exp/etcdrestore/main.go
- exp/etcdrestore/webhooks/installsh.go
- exp/etcdrestore/webhooks/rke2config.go
- exp/etcdrestore/webhooks/rke2config_test.go
- exp/etcdrestore/webhooks/suite_test.go
Adds RKE2Config webhook implementation
Fixes #498 
Part of: https://github.com/rancher/turtles/issues/388
**Checklist**:
> [etcdbackup&restore] Implement RKE2Config webhook

- CONTRIBUTING.md
- scripts/kind-cluster-with-extramounts.yaml
- scripts/turtles-dev.sh
The CAPI Operator Helm chart no longer installs cert-manager as a prerequisite. This PR changes the dev script to install cert-manager beforehand.
Also fixed the link to the dev guide.
**Checklist**:
> fix: Install cert-manager before capi-operator

- .github/dependabot.yaml
- Makefile
- Added dependabot job for etcd backup/restore
Fixes #649 
**Checklist**:
> Make generate updates etcd backup/restore modules

- charts/rancher-turtles/templates/azure-rbac.yaml
- charts/rancher-turtles/templates/clusterctl-config.yaml
- internal/controllers/capiprovider_controller.go
- internal/sync/azure_provider_sync.go
- internal/sync/provider_sync_test.go
Since the introduction of the flags upstream in
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4931
- https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4933
And implementing upstream https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4854, we need some changes to our turtles provider.
The CAPZ supports using different `GVK` for establishing controller to watch over changes within the bootstrap token. With that turtles will be able to leverage this flag for any user creating `azure` `CAPIProvider`.
The default value (**set to watch  `RKE2Config` for us**) of the CLI flag can be overridden, if the `CAPIProvider` resource has additionally specified:
```yaml
spec:
…
deployment:
containers:
- args: …
```
> ✨ Pass the new GVK flag to azure manager

- .github/workflows/e2e-long.yaml
- .github/workflows/e2e-short-test.yaml
- .github/workflows/e2e-short.yaml
- .github/workflows/run-e2e-suite.yaml
- Makefile
- test/e2e/config/operator.yaml
- test/e2e/const.go
- test/e2e/flags.go
- test/e2e/suites/embedded-capi-disabled-v3/suite_test.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/e2e/suites/update-labels/suite_test.go
- test/e2e/suites/v2prov/suite_test.go
- test/testenv/gitea.go
- test/testenv/rancher.go
- test/testenv/setupcluster.go
- test/testenv/turtles.go
This PR is a part of the E2E refactoring issue, it includes the following changes:
- Our suite setup includes a lot of duplicate code for setting up management clusters on different infrastructures, I moved all related code to the testenv package. Any potential users of this code can reuse it or take it as an example and implement their own in case their e2e suite setup differs from ours.
- Some E2E configuration options are passed partially through ginkgo flags and the YAML config. I started moving some options from flags to config files so we have a single place for most configurations. I will open a follow-up PR with moving other values too.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> Refactor E2E suite to make it more generic

- .github/workflows/e2e-long.yaml
- .github/workflows/run-e2e-suite.yaml
> Fix suite path in e2e setup

- test/e2e/data/rancher/rancher-setting-patch.yaml
For testing purposes we need to set agent-tls-mode to system-store. More details on the setting here: https://github.com/rancher/rancher/pull/45684
Fixes #
**Checklist**:
> Add new rancher setting patch in e2e

- .github/workflows/test_chart.yaml
- hack/ensure-kubectl.sh
- scripts/kind-cluster-with-extramounts.yaml
- test/e2e/config/operator.yaml
- test/e2e/data/cluster-templates/docker-rke2.yaml
- test/e2e/data/cluster-templates/vsphere-kubeadm.yaml
- test/e2e/data/cluster-templates/vsphere-rke2.yaml
Version 1.30.0 had issues collecting resources using `crust-gather`, due to https://github.com/kubernetes/kubernetes/issues/126739. 1.30.3+ no longer have this problem.
Fixes #
**Checklist**:
> 🌱 Use k8s 1.30.3

- charts/rancher-turtles/Chart.yaml
As we've now moved to newer version of CAPI (and related dependencies) https://github.com/rancher/turtles/commit/1a31ad4f04ea30ab0d2edff76c819c9bbfc2373d and this now requires Rancher v2.9 (as stated in the docs https://github.com/rancher/turtles-docs/pull/150) this change aligns the chart's lower/upper version bounds for Rancher. 
Fixes #
**Checklist**:
> chore: update lower/upper rancher version in chart

- .github/ISSUE_TEMPLATE/certification_request.yaml
As part of provider certification, this adds a new issue template for requesting a provider to be added to the list of Certified Providers once it is validated. This can be interesting for certain providers that we're not able to validate ourselves but users may be interested in using. After they certify the providers themselves,they can request it be added to the list and we can decide whether the provider is worth adding the main E2E suite so that it can be added to the Certified Table in the docs.
Fixes #680 
**Checklist**:
> feat: new issue template for provider certification

- api/v1alpha1/conditions_consts.go
- internal/sync/provider_sync.go
- internal/sync/provider_sync_test.go
- Perform check that CAPIProvider is up-to-date with current latest daily. Longer delay is set to prevent hitting github rate limits.
This change performs daily check for provider upgrades, and performs the actual upgrade automatically, if the `CAPIProvider` version is not set. If it is set, the version is user managed so we don’t upgrade this automatically.
Once upstream (capi-operator) has a condition to notify about new version availability, this daily check can be changed to rely on the status condition.
This change ensures we don’t leave existing users on older versions of providers.
Fixes …
> ✨ Check CAPI provider latest version daily

- docs/release.md
That is because bash expects straight quotes (" or ') for string delimiters.
Fixes #
**Checklist**:
> chore: Use straight quotes instead of curly in the git command

- charts/rancher-turtles/templates/clusterctl-config.yaml
- exp/etcdrestore/go.mod
- exp/etcdrestore/go.sum
https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.6.0
Even though tests for CAPRKE2 are not enabled yet (pending https://github.com/rancher/turtles/pull/634), bumping it to newer version to not forget.
Fixes #
**Checklist**:
> Bump CAPRKE2 to v0.6.0 version

- charts/rancher-turtles/templates/deployment.yaml
- feature/feature.go
> Remove etcd restore feature gate from code

- exp/etcdrestore/controllers/etcdsnapshot_secret_controller.go
- exp/etcdrestore/main.go
- exp/etcdrestore/webhooks/rke2config.go
- exp/etcdrestore/webhooks/rke2config_test.go
Follow-up on ownership references setting, to prevent leaving objects behind on removal.
Discussion Ref: https://github.com/rancher/turtles/pull/695#discussion_r1735863196
Fixes #
**Checklist**:
> 🌱 Perform ETCD snapshot restore ownership sync

- internal/controllers/capiprovider_controller.go
CAPI provider reconciler is re-applying proxied provider during deletion phase, causing re-creation of the infra resources. This change prevents it from happening.
Deletion will need to be performed according to https://turtles.docs.rancher.com/getting-started/uninstall_turtles
Fixes #704
**Checklist**:
> 🐛 Skip CAPIProvider reconciliation on deletion timestamp

- test/e2e/data/cluster-templates/docker-rke2.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
- test/e2e/suites/import-gitops/import_gitops_test.go
Released version 0.6.0 is not currently tested in rancher turtles.
Fixes #
**Checklist**:
> Re-enable RKE2 tests for 0.6.0 version, after migration

- charts/rancher-turtles/templates/pre-install-job.yaml
- charts/rancher-turtles/values.yaml
- internal/controllers/capiprovider_controller.go
- internal/controllers/capiprovider_controller_test.go
- main.go
This change should allow to install turtles in development scenario without dependency on rancher, for the expense of added requirement to patch the `embedded-cluster-api` feature gate manually.
This can be done by specifying `--set rancherTurtles.rancherInstalled=false` flag.
Deletion will need to be performed according to https://turtles.docs.rancher.com/getting-started/uninstall_turtles
Fixes #627
**Checklist**:
> 🌱 Add option to skip rancher pre-requisites

- exp/etcdrestore/controllers/etcdmachinesnapshot_controller.go
Follow-up to https://github.com/rancher/turtles/pull/708#pullrequestreview-2277177404
Fixes #
**Checklist**:
> Improvements to EtcdMachineSnapshot controller

- docs/adr/0012-clusterctl-provider.md
This change will add a configurability layer on top of the default state of the `clusterctl.yaml` `ConfigMap`, exposed to users as a public API.
Fixes #
**Checklist**:
> ADR: Clusterctl Config resoruce

- charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml
- exp/etcdrestore/api/v1alpha1/etcdmachinesnapshot_types.go
- exp/etcdrestore/config/crd/bases/turtles-capi.cattle.io_etcdmachinesnapshots.yaml
- exp/etcdrestore/controllers/planner.go
> Implement Planner for system-agent integration

- .github/workflows/e2e-short.yaml
We run e2e tests in every PR and current workflow defines the type of actions to run e2e short tests are as following:
```
on:
pull_request:
types: [opened, edited, synchronize, reopened, labeled, unlabeled]
```
Description of each activity type:
- opened: Triggered when a new pull request is opened.
- edited: Triggered when an existing pull request is edited.
- synchronize: Triggered when a pull request's head branch is updated (e.g., new commits are pushed to the branch).
- reopened: Triggered when a closed pull request is reopened.
- labeled: Triggered when a label is added to a pull request.
- unlabeled: Triggered when a label is removed from a pull request.
Personally, it seems too much to re-run whole e2e-short tests when just editing PR …
> Run short e2e tests only for code changes

- charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml
- exp/etcdrestore/config/rbac/role.yaml
- exp/etcdrestore/config/webhook/manifests.yaml
- exp/etcdrestore/main.go
- exp/etcdrestore/webhooks/etcdmachinesnapshot.go
- exp/etcdrestore/webhooks/etcdsnapshotrestore.go
- exp/etcdrestore/webhooks/rbac.go
- exp/etcdrestore/webhooks/rbac_test.go
- exp/etcdrestore/webhooks/rke2config_test.go
Add a validating webhook for ETCD snapshot and restore that validates users permissions for the referenced cluster object.
Fixes https://github.com/rancher/turtles/issues/721
**Checklist**:
> Add webhook that validated users RBAC rules

- .github/workflows/nightly-chart-and-image-publish.yaml
- .github/workflows/release_build/action.yaml
- .github/workflows/release_sign/action.yaml
- .github/workflows/trivy.yml
- Makefile
- test/e2e/config/operator.yaml
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- test/e2e/suites/embedded-capi-disabled-v3/suite_test.go
- test/e2e/suites/embedded-capi-disabled/suite_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
- test/e2e/suites/migrate-gitops/suite_test.go
- test/e2e/suites/update-labels/suite_test.go
- test/e2e/suites/v2prov/suite_test.go
This PR adds a recursive signing of the published manifest. The manifest digest is saved in a temp file specified by `--iidfile` flag, this is the only way to get the image digest without requesting it from the remote registry as buildx doesn't store anything locally.
Fixes #
**Checklist**:
> Sign published turtles manifest and all underlying images

- Makefile
Fix Build and Publish nightly Helm chart and Docker images [GHA](https://github.com/rancher/turtles/actions/runs/10921160897/job/30313118202)
Fixes #
There are couple of issues with how we currently construct  `RELEASE_TAG`, `PREVIOUS_TAG` and `HELM_CHART_TAG` env vars in Makefile. 
1. As is without this change, when you run `make release-chart`, chart is built and values.yaml looks like below(truncated version):
```
rancherTurtles:
image: ghcr.io/rancher/turtles
imageVersion: test/v0.11.0
imagePullPolicy: IfNotPresent
namespace: rancher-turtles-system …
```
> 🐛 Fix build and publish nightly Helm chart workflow

- api/v1alpha1/clusterctl_config_types.go
- api/v1alpha1/conditions_consts.go
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- config/crd/bases/turtles-capi.cattle.io_clusterctlconfigs.yaml
- go.mod
- internal/controllers/clusterctl/config.go
- internal/controllers/clusterctlconfig_controller.go
- internal/sync/provider_sync.go
- internal/sync/provider_sync_test.go
- internal/test/helpers/envtest.go
- main.go
- test/e2e/helpers.go
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- test/framework/turtles.go
Fixes #599
Fixes #691 
**Checklist**:
> Use local clusterctl overrides for determining latest version for provider

- exp/etcdrestore/controllers/etcdsnapshot_secret_controller.go
> Fix SSA patching in etcd snapshot restore secret sync

- internal/controllers/clusterctl/config.yaml
kind/feature
The Elemental CAPI provider just got a new release: https://github.com/rancher-sandbox/cluster-api-provider-elemental/releases/tag/v0.7.0
> Bump elemental provider version

- api/v1alpha1/capiprovider_types.go
- api/v1alpha1/capiprovider_wrapper.go
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
- internal/controllers/capiprovider_controller_test.go
- internal/sync/provider_sync.go
Ensure that we always display provider name, which defaults to `.spec.name OR .metadata.name` in the `-o wide` of kubectl or UI, in cases when the name is not set in the spec.
Fixes #630 
**Checklist**:
> 🐛 CAPIProvider: Always provide a name for UI and -o wide

- exp/etcdrestore/webhooks/rke2config.go
- exp/etcdrestore/webhooks/rke2config_test.go
Executing command with `sudo` prefix fails to provision agent on RKE2 clusters. More context in #763 
Fixes #763 
**Checklist**:
> 🐛 Drop sudo from system agent install command

- docs/release.md
Going forward, when a new  Turtles minor/major release will be published, we need to make sure Turtles Product Docs is synced and contains up-to-date versions of docs available for users. This patch adds notes about additional post-release step to releasing documentation about syncing the Community Docs of Turtles with the Product Docs available in https://documentation.suse.com/cloudnative/cluster-api/v0.11/en/index.html
Fixes #
Reference JIRA [ticket](https://jira.suse.com/browse/SURE-9171) to sync v0.12 Community Docs version with Product Docs. …
> 📖 Add additional post-release step to release docs

- .github/workflows/nightly-chart-and-image-publish.yaml
- Makefile
- PROJECT
- exp/README.md
- exp/etcdrestore/Dockerfile
- scripts/turtles-dev.sh
This patch provides an alternative way to run Rancher Turtles locally using the turtles-dev script and Tilt. A new `USE_TILT_DEV` env var was introduced (set to true by default to keep previous behaviour), and a new way of deploying Turtles uses the locally built helm chart only when set to `false`. 
Additionally, image building for new `turtles-etcd-snapshot-restore` was taken care by Tilt when used, however it is not when there is no Tilt. To run it without tilt, new Dockerfile to build the image for etcdrestore controller and use the built image in local testing. 
Lastly, it changes nightly image publish GH action to publish etcdrestore image as part of the GHA.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
> 🌱 Add a way to run ETCDRestore controller locally

- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Nightly E2E tests are systematically failing and the common issue is the Docker+RKE2 test case. This may be related to some memory limits (@Danil-Grigorev noticed something similar in short E2E test executions) because I've had the tests passing locally in multiple tries.
For now, I suggest we disable this specific scenario, as **it is adding noise to our nightly tests which we no longer can rely on for detecting unexpected failures**. Let's see if disabling this improves the health of these tests. I'd say there's no harm in disabling this, as testing CAPD scenarios is not that relevant in nightly E2E.
Fixes #755
My suggestion is to try to stabilize tests and, once we accomplish …
> test: disable docker/rke2 e2e scenario

- internal/sync/azure_provider_sync.go
- internal/sync/secret_sync.go
- internal/sync/secret_sync_test.go
- test/e2e/const.go
- test/e2e/data/capi-operator/capa-variables.yaml
- test/e2e/data/capi-operator/capi-providers-legacy.yaml
- test/e2e/data/capi-operator/capi-providers.yaml
- test/e2e/data/capi-operator/capv-provider.yaml
- test/e2e/data/capi-operator/full-providers.yaml
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
This change improves the process of `CAPIProvider` creation. Users don’t need to specify `spec.configSecret` at all times, in order to get default set of enabled features, such as ClusterClasses or MachinePools, + provider specific features.
Fixes #787
**Checklist**:
> 🐛 Remove requirement to specify CAPIProvider secret

- .dockerignore
- .github/workflows/e2e-long-test.yaml
- .github/workflows/e2e-short-test.yaml
- .github/workflows/e2e-short.yaml
- .github/workflows/run-e2e-suite.yaml
- .github/workflows/trivy.yml
- .gitignore
- Makefile
Cache e2e image builds
Fixes #
**Checklist**:
> Cache e2e image builds

- .github/workflows/e2e-long-test.yaml
- .github/workflows/run-e2e-suite.yaml
azure-janitor is now under rancher organization
Changing `azure-janitor` URL as it is now under `rancher` organization. The old `rancher-sandbox` is redirecting to `rancher` but at some point we won't be able to execute the action from this URL as it'll probably be removed from the list of allowed actions and only actions under `rancher` can be executed.
Fixes #
**Checklist**:
> chore: fix azure janitor action url

- updatecli/updatecli.d/manifest.yaml
Updatecli is not signing automatically generated commits which goes against Turtles' requirements. Simply by committing changes using GitHub API, which updatecli allows via `commitusingapi`, all commits created by the bot are automatically signed: https://github.com/updatecli/updatecli/pull/2046
Fixes #
**Checklist**:
> fix: sign updatecli commits

- exp/etcdrestore/webhooks/rbac.go
- exp/etcdrestore/webhooks/rbac_test.go
Our controller is not currently allowed to create ETCDMachineSnapshot due to lack of permissions from the SAR point of view.
It is easy to identify the controller by the use of our ServiceAccount:
`system:serviceaccount:rancher-turtles-system:rancher-turtles-etcdsnapshotrestore-manager`
Fixes #768 
**Checklist**:
> Permit turtles controller to access the cluster

- exp/etcdrestore/controllers/etcdsnapshotsync_controller.go
A panic occurred during testing ClusterClass usage together with exp. EtcdSnapshot controller running, which may be forgotten later. This is a small fix to address that.
Fixes #
**Checklist**:
> Fix panic in webhook for CC clusters

- docs/release.md
Simply fixing a minor typo in link to Jira and also removing the labeling step when creating a new docs release as it should now be automatically [tagged on PR creation](https://github.com/rancher/turtles-docs/blob/654552cef8b2b12b9275f7273fd69fdc98b295a4/.github/workflows/version-publish.yaml#L43). 
Fixes #
**Checklist**:
> docs: fix broken jira link

- Makefile
- exp/etcdrestore/Dockerfile
Remove some unused variables from `Makefile` and etcdrestore image build process.
Fixes #824 
I simply moved `docker-build` up and `docker-build-etcdrestore` down, so Turtles appears before etcdrestore, and added a sub-section title, but Git got confused and reported all these changes. Essentially it should just be a switch in order.
**Checklist**:
> Build image streamline

- .github/workflows/trivy.yml
This is taken from @yiannistri's https://github.com/rancher/aks-operator/pull/718 and since we're also experiencing these issues in Turtles, I thought it's worth adding it here too. 
> @yiannistri:
>
> We frequently get CI failures when scanning with trivy because there have been too many requests to download the vulnerability db from the rancher org (because many of its repos are using it).
>
> This PR updates the Scan workflow to include additional repositories to be used if trivy fails to retrieve the vulnerability db from the primary source.
Fixes #
Source for fix: https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-10884984
**Checklist**:
> chore: fix trivy timeout

- internal/sync/provider_sync_test.go
- test/e2e/const.go
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- test/e2e/suites/update-labels/suite_test.go
- updatecli/updatecli.d/manifest.yaml
Based on observed failure during CI execution in #835.
We perform e2e tests and integration tests, which ensure that a new turtles release will update `latest` target for provider, and will perform upgrade if the `latest` is set on `CAPIProvider`.
Current updatecli PRs don’t modify these values, which leads to CI failures after any `core` provider version changes.
Testing is performed on https://github.com/Danil-Grigorev/rancher-turtles/pull/5, which is created using `make updatecli-apply`
Fixes #
**Checklist**:
> [updatecli] Perform replacement of `CAPIVersion` in tests and e2e

- exp/etcdrestore/webhooks/rke2config.go
- exp/etcdrestore/webhooks/rke2config_test.go
Deploy system-agent only on RKE2 CP nodes. According to https://docs.rke2.io/backup_restore#restoring-a-snapshot-to-existing-nodes, the process only requires to stop rke2-server on all CP nodes.
Fixes #762 
**Checklist**:
> 🌱 Patch RKE2 config only for CP machines

- internal/controllers/helpers.go
- internal/controllers/import_controller.go
- internal/controllers/import_controller_v3.go
- internal/controllers/import_controller_v3_test.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
- util/annotations/helpers.go
Preparing for new Rancher release that will include a feature that allows to bypass setting a creator owner on the resource. Import controller now adds the annotation `field.cattle.io/no-creator-rbac` on any Rancher clusters it reconciles. This will apply to newly created clusters and to existing ones that are subject to reconciliation.
You can take a look at https://github.com/rancher/rancher/pull/47259, where this new option is introduced.
Fixes #
Also updates E2E and import controller tests to check that clusters are properly annotated.
**After this is merged, we'll have to wait until next Rancher minor release to consider this as done**
**Checklist**:
> feat: opt out of cluster owner rbac

- charts/rancher-turtles/templates/core-provider.yaml
In #454 the pre-delete hook was removed from the `Namespace` and in #508 it was removed from the `CAPIProvider`
However the pre-delete hook remains on the `ConfigMap`, which means if installation fails for any reason prior to creating the `Namespace` in the `post-install` hook, the chart can become undeletable with an error like:
```
+ helm_v3 uninstall rancher-turtles --namespace rancher-turtles-system --wait Error: warning: Hook pre-delete rancher-turtles/templates/core-provider.yaml failed: 1 error occurred:
* namespaces "capi-system" not found
```
Note the error above is from the [RKE2 helm controller](https://docs.rke2.io/helm), where the ability to uninstall a chart after any temporary installation error is particularly important, since the …
> chart: core-provider remove inconsistent pre-delete hook

- Tiltfile
- config/capiproviders/bootstrap.yaml
- config/capiproviders/controlplane.yaml
- config/capiproviders/core.yaml
- config/capiproviders/docker.yaml
- config/capiproviders/kustomization.yaml
- scripts/turtles-dev.sh
- tilt-settings.json.example
- tilt/project/Tiltfile
Improves dev environment setup for turtles, making it use actual turtles chart capi-operator as a dependency, as opposed to installing upstream one separately.
This allows to rely on `CAPIProvider` versions when deploying providers, so incompatibility in providers matrix is eliminated based on centralization of the providers version management.
Additionally this makes dev-env adhere to supported configuration described in turtles docs (more closely), and improves development process for etcd snapshot restore and other features.
Fixes #
**Checklist**:
> 🌱 Install capi-operator as a turtles dependency in a dev-env

- internal/controllers/clusterctl/config.yaml
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- test/framework/turtles.go
Ensure that every provider in the overrides list has an injected image for the provisioned workloads from the downstream builds. This works on a couple of assumptions:
1. CAPI Operator in installed as a turtles dependency
2. `CAPIProvider` is updated/created/re-created after a version with this patch is used. No in-place update will happen for existing providers, unless a version of the provider changes.
Fixes #
**Checklist**:
> 🌱 Add image overrides for certified providers

- charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml
- exp/etcdrestore/api/v1alpha1/etcdmachinesnapshot_types.go
- exp/etcdrestore/api/v1alpha1/zz_generated.deepcopy.go
- exp/etcdrestore/config/crd/bases/turtles-capi.cattle.io_etcdmachinesnapshots.yaml
- exp/etcdrestore/controllers/etcdmachinesnapshot_controller.go
- test/e2e/config/operator.yaml
- test/e2e/helpers.go
- test/e2e/specs/etcd_snapshot_restore.go
- test/e2e/suites/etcd-snapshot-restore/etcd_snapshot_restore_test.go
- test/go.mod
Adds simple e2e scenario for performing ETCD snapshot and restore. Tests will run as nightly, which use EKS LB and allows to pull agent image from rancher without issues.
Fixes #502
**Checklist**:
> [etcd-snapshot-restore] Snapshot/restore e2e test

- internal/controllers/clusterctl/config.yaml
- internal/sync/provider_sync_test.go
- test/e2e/const.go
<Actions>
<action id="de1864defccec55be9eca14576e5f510cb8e6dff35da988bd035728bd05d2e38">
<h3>Bump CAPI providers version</h3>
<details id="3ed7f6a16f7c5ae011028e586a98d12d2cf04c6ccd3bb2388b934a8dcc15f28a">
<summary>bump core capi</summary>
<p>1 file(s) updated with &#34;https://github.com/rancher-sandbox/cluster-api/releases/v1.8.4/&#34;:&#xA;&#x9;* ./internal/controllers/clusterctl/config.yaml&#xA;</p>
<details>
<summary>v1.8.4</summary>
<pre>&#xA;Release published on the 2024-10-31 18:53:46 +0000 UTC at the url https://github.com/rancher-sandbox/cluster-api/releases/tag/v1.8.4&#xA;&#xA;Release v1.8.4</pre>
</details>
</details>
<details id="6398ece5782b168b1428bef95905202626692569f08c8d33ea956f7249f94562">
<summary>bump core capi in tests package</summary>
<p>1 file(s) updated with …
> [updatecli] Bump CAPI Providers versions

- .github/workflows/run-e2e-suite.yaml
It looks like this was accidentally removed. Building and pushing e2e images is required when EKS is used as a management cluster since it doesn't have a local registry.
Fixes #
**Checklist**:
> Build and push e2e images

- Dockerfile
- Makefile
- Tiltfile
- charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml
- exp/etcdrestore/config/default/manager_image_patch.yaml
- scripts/turtles-dev.sh
- test/e2e/config/operator.yaml
We need to build etcd snapshot/restore image together with turtles, to utilize same build and release path.
Fixes #895 
**Checklist**:
> Unify etcd snapshot-restore image with turtles

- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/specs/migrate_gitops_provv1_mgmtv3.go
Reverts rancher/turtles#883
Should be passing now, since `eks` e2e tests use built image from the main branch
> Revert "Disable e2e verification for NoCreatorRBAC annotation in AWS and Azure"

- .github/workflows/run-e2e-suite.yaml
- Makefile
Use `docker build` instead of `buildx` for e2e because `buildx` takes too much for a test image to build.
Fixes https://github.com/rancher/turtles/issues/893
**Checklist**:
> Use docker build for e2e image

- charts/rancher-turtles/templates/deployment.yaml
- config/manager/manager.yaml
Deploying a local test environment `make dev-env` I noticed the controller manager could not start:
```
NAMESPACE                   NAME                                                              READY   STATUS              RESTARTS       AGE
rancher-turtles-system      rancher-turtles-controller-manager-d8ff6d887-w6qzq                0/1     OOMKilled           30 (5m6s ago)    5h58m
```
Once I increased the limits (as per PR) it did start correctly and seems to be idling at `223Mi`:
```
> kubectl -n rancher-turtles-system top pods
NAME                                                    CPU(cores)   MEMORY(bytes)   
rancher-turtles-cluster-api-operator-598c6d8cbc-z877q   3m           49Mi …
```
> Increase manager memory limit

- internal/controllers/capiprovider_controller_test.go
- internal/sync/client.go
- internal/sync/core.go
- internal/sync/interface.go
- internal/sync/interface_test.go
- internal/sync/secret_mapper_sync.go
- internal/sync/secret_sync.go
Secret sync and variables sync methods issue SSA patch request to the same resource, but there appears to be an issue with the usage of the SSA patch field owner.
Previously the resource was patched with 2 different patches in the same reconcile loop, but both were using same owner, which caused infinite RV bumps on the provider secrets, as each patch conflicted with another, issued by the same owner.
Using different field owners fixes this issue.
Fixes #914
**Checklist**:
> :bug: Fix diff check on secret sync

- internal/controllers/import_controller_v3.go
- internal/controllers/patch_kcfg_controller.go
- internal/sync/core.go
This change remove usages of retry from the code, which improves situation with stuck tests on general timeout in local and CI runs. The object which is retried with patch is using `MergeFromWithOptimisticLock` and the object is never updated, so this retry will never succeed.
Fixes #912 
**Checklist**:
> 🌱 Remove retry usages across the code

- internal/controllers/capiprovider_controller.go
- internal/sync/client.go
- internal/sync/core.go
- internal/sync/core_test.go
The CAPIProvider syncing secret is getting a new `resourceVersion` even on empty patch. This creates an infinite loop where the CAPIProviderReconciler is continuously invoked due to the secret version change.
This PR tries to address this, however further issues escalate after applying it. 
For example there is a conflict between the `rancher-turtles-controller-manager` and the `cluster-api-operator` when it comes to managing some resources. 
For example giving the following bootstrap, there is a conflict in how finalizers are handled:
```yaml
kind: BootstrapProvider
metadata:
annotations:
operator.cluster.x-k8s.io/applied-spec-hash: d637e476cb631c683729765c7f6f3fd8c04b5c314254b114aa9500b51b7ed8f1 --> Emptied/Re-filled on a race condition …
```
> Prevent infinite CAPIProvider reconciliations

- charts/rancher-turtles/templates/deployment.yaml
- feature/feature.go
- internal/controllers/helpers.go
- internal/controllers/import_controller_v3.go
- internal/controllers/import_controller_v3_test.go
- internal/controllers/suite_test.go
With introduction of https://github.com/rancher/rancher/pull/46672 `managementv3` clusters annotated with `provisioning.cattle.io/externally-managed` will omit creating fleet cluster automatically with the instance. This allows `CAAPF` to fully manage fleet cluster lifecycle workflow, which will no longer be [duplicated](https://github.com/rancher/turtles/issues/622).
This PR allows to gauge the setting under the `addon-provider-fleet` feature gate.
Fixes #
**Checklist**:
> ✨ Populate fleet external annotation on management clusters

- Tiltfile
- tilt/project/Tiltfile
Add Tilt support for etcd snapshot restore, Tilt will build a separate image for every subproject we add. 
Fixes #
**Checklist**:
> Support tilt hot reload for etcd snapshot restore

- .github/workflows/e2e-short.yaml
- .github/workflows/run-e2e-suite.yaml
- Makefile
Closes #907 
This PR should automatically cleanup the e2e test images after the job is done.
Note that the images are deleted even in case of job failure. I can change the behavior and keep them in case of failure for further investigation when job fails, I just not find it worth it since you can easily rebuild them.
Also the images will be tagged with the job number and attempt, instead that just `v0.0.1`, so that they can be referenced.
> Use deterministic tag for e2e-images and cleanup after use

- .github/workflows/e2e-image-clean.yaml
- .github/workflows/e2e-image-publish.yaml
- .github/workflows/e2e-long.yaml
- .github/workflows/run-e2e-suite.yaml
This PR is to fix the e2e workflow and bring some improvements.
The turtles-e2e image is now only built once as pre-requisite job. I kept the `v0.0.1` tag because changing this has further implications down the line and should be propagated better, for example to the helm chart values and the `test/e2e/config/operator.yaml` file. 
The image is also now deleted correctly always, when all parallel jobs end.
See: https://github.com/rancher/turtles/pkgs/container/turtles-e2e
Sample run: https://github.com/rancher/turtles/actions/runs/12595032471
> Additional e2e fixes

- Makefile
- api/rancher/management/v3/setting.go
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/deployment.yaml
- charts/rancher-turtles/values.yaml
- feature/feature.go
- go.mod
- internal/controllers/helpers.go
- internal/controllers/helpers_test.go
- internal/controllers/import_controller.go
- internal/controllers/import_controller_v3.go
After merging this PR, users can leverage CA certs stored in Rancher setting to import CAPI clusters.
Fixes https://github.com/rancher/turtles/issues/847
**Checklist**:
> Add ability to leverage agent tls mode setting

- Tiltfile
- charts/rancher-turtles/templates/rancher-turtles-exp-etcdrestore-components.yaml
- exp/etcdrestore/config/default/manager_image_patch.yaml
- tilt/project/Tiltfile
Tilt uses own process for building docker images, which does involve overriding built image `CMD`. This overlaps with the model etcd snapshot restore is currently following, where the image is the part of the regular turtles image, running under different `CMD`.
This discrepancy causes e2e to fail, and `Tiltfile` based build to work without issues.
Current change ensures that both `tilt up` and `GINKGO_LABEL_FILTER=local make test-e2e` work without issues.
```
RESOURCE NAME                                                                     CONTAINER •  UPDATE STATUS  •    AS OF 
▶ ● (Tiltfile) ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌ N/A             • <45s ago 
● turtles_controller …
```
> Use correct binary path for snapshot/restore, adapt Tilt config

- charts/rancher-turtles/templates/post-delete-job.yaml
- charts/rancher-turtles/templates/post-upgrade-job.yaml
- charts/rancher-turtles/templates/pre-delete-job.yaml
- charts/rancher-turtles/templates/pre-install-job.yaml
Removes the hardcoded namespace values used within the different chart hooks.
There are some resources created in the default namespace across the `pre-install-job` and `post-upgrade-job` hooks. Should those be updated as well?
- https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/templates/post-upgrade-job.yaml#L54
- https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/templates/pre-install-job.yaml#L7
- https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/templates/pre-install-job.yaml#L61
- https://github.com/rancher/turtles/blob/main/charts/rancher-turtles/templates/pre-install-job.yaml#L83
**Checklist**:
> charts: Replace hardcoded namespaces

- test/e2e/data/cluster-templates/docker-rke2.yaml
- test/e2e/data/cluster-templates/vsphere-rke2.yaml
This will change all templates to use `RKE2ControlPlane.spec.machineTemplate`
Related to https://github.com/rancher/cluster-api-provider-rke2/pull/542
Fixes #
**Checklist**:
> Use RKE2ControlPlane.spec.machineTemplate

- exp/etcdrestore/webhooks/install.sh
- exp/etcdrestore/webhooks/rke2config.go
- exp/etcdrestore/webhooks/rke2config_test.go
- test/e2e/data/cluster-templates/docker-rke2.yaml
- test/e2e/suites/etcd-snapshot-restore/etcd_snapshot_restore_test.go
- util/annotations/helpers.go
We need to allow alternative installation methods for the rancher `system-agent` binary. Users may want either:
- Pre-load system agent in the image manually via cloud-config or other means in the air-gapped installation scenario
- Use github release to download agent binary
This change allows to perform both via added annotations on the CAPI `Cluster` object.
Examples:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster 
metadata:
name: rke2-cluster
annotations:
cluster-api.cattle.io/upstream-system-agent: "true" # Install agent binary from github repo release
```
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster 
metadata:
name: rke2-cluster
annotations:
cluster-api.cattle.io/local-system-agent: …
```
> Permit using github release or preloaded binary for system-agent

- Makefile
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- config/rbac/role.yaml
- internal/controllers/import_controller_v3.go
Looks like the RBAC rules where never correctly generated. 
This is an attempt to fix it, should also fix #989 
Fixes #989
**Checklist**:
> Fix missing kubebuilder generation

- exp/etcdrestore/webhooks/rke2config_test.go
- internal/sync/secret_sync_test.go
> Use eventually() in etcd restore tests

- scripts/turtles-dev.sh
This PR pulls Rancher image once and re-use it in the dev setup created using `make dev-env`. Currently, if a developer does `make dev-env` the Rancher image is pulled as a part of `helm install rancher`. If the developer deletes the `kind` cluster created using `make dev-env` and creates a new one, Rancher image will be pulled again because this pulling happens inside the kind node. Hence, the need to "cache" it.
Fixes: N/A
Please let me know if there's a better way to do this, or if there's already a way to do it that I'm not aware of. 🙂 
On the flip side, …
> Download Rancher image only once

- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- charts/rancher-turtles/values.yaml
- feature/feature.go
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
- test/e2e/suites/import-gitops/suite_test.go
Enable CAAPF by default for all imported CAPI clusters.
Cluster or namespace may specify `cluster-api.cattle.io/disable-fleet-auto-import` label to exclude it from automatic import process with fleet.
Fixes #1002 
**Checklist**:
> Enable CAAPF by default

- updatecli/updatecli.d/manifest.yaml
Add CAPG to `updatecli`'s configuration so it is automatically bumped.
Fixes #
**Checklist**:
> chore: add capg to list of updatecli providers

- .github/workflows/nightly-chart-and-image-publish.yaml
Makefile target `docker-build-and-push-etcdrestore` was removed in https://github.com/rancher/turtles/pull/897 . Also `HELM_EXPERIMENTAL_OCI` should not be required for Helm >= 3.8.0 and the Go compiler should not be needed since we're building inside a container.
**Checklist**:
> ci: Remove incorrect make target

- main.go
kind/feature
Just a little notification to explicitly tell the user this setting is enabled.
I'm also open to make this an Error instead for more visibility.
Fixes #
**Checklist**:
> Notify user when insecure-skip-verify is active

- test/testenv/rancher.go
Fixes #1009
This PR only fixes the `CATTLE_FEATURES` notation that is currently ineffective.
> Fix Rancher chart features value

- internal/controllers/clusterctl/config.go
If new provider is added through clusterctlconfig:
1. which does not exist in the current config map it will be added as new entry to configmap
2. with new URL and  if provider exists, it only updates the URL of that entry
3. without any changes to URL and if provider exists, it stays as is without any changes.
I am planning to add tests as a follow up PR, since config.go anyways did not have a dedicated test file up until now.
**Checklist**:
> Support deduplication when using ClusterctlConfig

- docs/adr/0013-self-managed-rancher-cluster.md
This is an ADR proposal for the Self managed cluster.
Some proof of concept for a simple provisioning script can be found [here](https://github.com/anmazzotti/rancher-turtles/blob/self_managed_rancher_cluster/scripts/bootstrap-cluster.sh).
Fixes #984
**Checklist**:
> ADR: Self managed Rancher cluster

- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/post-delete-job.yaml
- charts/rancher-turtles/values.yaml
Move `features.cluster-api-operator` under `cluster-api-operator` in `values.yaml` file.
Fixes #1022
**Checklist**:
> chore: cleanup cluster-api-operator features in chart values

- internal/controllers/clusterctl/config_test.go
Adds unit test for the deduplication feature implemented in https://github.com/rancher/turtles/pull/1011
Fixes #761
**Checklist**:
> 🌱 Add unit tests for ClusterConfig

- Dockerfile
Use cross-compilation when building the image with `buildx`. This means that the process does not need to use emulation for the whole build which makes it considerably faster.
We can use the existing build arguments (which are globally available):
- `BUILDPLATFORM`: make the image always native to the machine.
- `TARGETOS` and `TARGETARCH`: configure the compiler process for the specific architecture.
Fixes #933 
I ran a quick test and image building is a few minutes faster after this change.
**Checklist**:
> feat: add dockerfile cross-compilation for multi-platform images

- Makefile
- scripts/turtles-dev.sh
`make dev-env`  and `make clean-dev-env`  default to using `capi-test`. This PR allows a different name to be used, if set. Also, updated to use ngrok-operator and eliminated a couple of errors from Helm.
**Checklist**:
> fix: Make dev cluster name configurable

- docs/release.md
This PR introduces a couple of post-release steps:
1. After a new release is published, a "human readable" description has to be added to the start of the release notes.
2. Run `Updatecli` action in `turtles-docs` to automatically generate the `Changelog` for the new release -> merge PR before publishing docs.
Fixes #
**Checklist**:
> docs: add post-release step for release notes

- exp/etcdrestore/go.mod
- exp/etcdrestore/go.sum
- internal/controllers/clusterctl/config.yaml
- internal/controllers/clusterctl/config_test.go
Bump CAPRKE2 to v0.11.0.
Fixes #1053 
**Checklist**:
> Bumps CAPRKE2 to v0.11

- charts/rancher-turtles/templates/post-upgrade-job.yaml
Now that there's a single method for importing clusters via `clusters.management.cattle.io` (v3) and migration is automatically applied for all `clusters.provisioning.cattle.io` (v1) we no longer have values in the Helm chart that control when Rancher clusters deletion is applied ([this](https://github.com/rancher/turtles/commit/1f6972edaea0c05de2406a9bd3020f8171a67576#diff-c0588fa3a386b0b96a535569bdd77004aa57407c73e52c49502cfd52a46eb23d) is where the changes are introduced).
In this case, as reported by @cpinjani [here](https://github.com/rancher/turtles/issues/1061), CAPI clusters are being un-imported after upgrade because the post-upgrade job deletes all v3 cluster resources and then the controller labels the CAPI cluster `imported=true`. For …
> fix: remove v1 clusters for migration in post-upgrade job

- exp/etcdrestore/controllers/etcdsnapshotsync_controller.go
- exp/etcdrestore/controllers/snapshotters/rke2snapshotter.go
- exp/etcdrestore/main.go
Currently, when a snapshot gets deleted from the cluster, the corresponding `ETCDMachineSnapshot` resource is left behind with a status of `Done`. This PR aims to address that by removing such resources if a corresponding `ETCDSnapshotFile` resource is not found in the downstream cluster.
Fixes #719 
**Checklist**:
> fix: Delete ETCDMachineSnapshot resources if their corresponding snapshot gets deleted

- .github/ISSUE_TEMPLATE/certification_request.yaml
- CONTRIBUTING.md
- README.md
- docs/adr/0012-clusterctl-provider.md
- test/e2e/README.md
This PR fixes documentation links within the repo.
Fixes #
**Checklist**:
> Fix documentation links

- Makefile
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/rancher-turtles-exp-day2-components.yaml
- charts/rancher-turtles/templates/rancher-turtles-exp-day2-deployment.yaml
- charts/rancher-turtles/values.yaml
- exp/day2/config/chart/kustomization.yaml
- exp/day2/config/chart/kustomizeconfig.yaml
- exp/day2/config/chart/manager_role_aggregation_patch.yaml
- exp/day2/config/chart/webhookcainjection_patch.yaml
- exp/day2/feature/feature.go
- exp/day2/feature/gates.go
- exp/day2/main.go
- scripts/turtles-dev.sh
- test/e2e/suites/etcd-snapshot-restore/suite_test.go
This PR updates `questions.yaml` in order to allow a user to enable/disable the ETCD Backup/Restore functionality from the Rancher UI. 
There are now two new checkboxes available during Turtles installation:
- `Enable Day 2 Operations functionality in Rancher Turtles` which is used to deploy the day 2 operations deployment and associated service account
- `Enable ETCD Backup and Restore` which is used to deploy the CRDs, RBAC and webhooks needed for the ETCD backup/restore functionality. 
The idea is to be able to deploy a subset of the day 2 operations.
Fixes #849 
**Special notes for your …
> feat: Alow user to enable/disable day 2 operations from Rancher UI

- exp/day2/main.go
The day 2 controller was crash looping as its deployment expected liveness and readiness checks that were missing. Noticed on the Tilt UI.
Fixes #
**Checklist**:
> fix: Add readiness/liveness check

- internal/sync/secret_mapper_sync.go
- internal/sync/secret_mapper_sync_test.go
> Use Rancher secret key names for vSphere in secret mapper

- test/e2e/README.md
- test/e2e/data/capi-operator/capv-variables.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Updated CAPV tests to ensure the correct providers are set up before test execution:
- RKE2 test was not setting up CAPV provider.
- Kubeadm test was not setting up Kubeadm bootstrap and control plane providers.
The vSphere secret was also renamed to match provider name otherwise it failed to install. 
Fixes #
**Checklist**:
> test: Ensure CAPV tests have the correct providers set up

- test/e2e/config/operator.yaml
https://github.com/rancher/turtles/commit/5526153a15d534d15c3b71e63510c9073e52c8bd renames `CPI_IMAGE_VERSION` env variable defined in `test/e2e/config/operator.yaml` to `CPI_IMAGE_K8S_VERSION` in cluster templates only. This PR renames/updates the variable name in the file where it is defined. 
Fixes #
**Checklist**:
> 🐛 Rename `CPI_IMAGE_VERSION` variable to `CPI_IMAGE_K8S_VERSION`

- .github/workflows/nightly-chart-and-image-publish.yaml
- .github/workflows/nightly-test-release.yaml
- .github/workflows/release-workflow.yaml
- .github/workflows/test_chart.yaml
Set `GH_TOKEN` env variable in all GHAs' where `Package operator chart` step is run (which under the hood runs [make release-chart](https://github.com/rancher/turtles/blob/main/Makefile#L579-L582)) to make sure `RELEASE_NOTES.md` is generated properly
Fixes #1084 
**Checklist**:
> Set `GH_TOKEN` env variable to properly generate `RELEASE_NOTES.md` file

- examples/applications/azure/clusterresourceset-cloud-provider.yaml
- examples/clusterclasses/azure/clusterclass-example.yaml
- test/e2e/const.go
- test/e2e/data/capi-operator/capz-identity-secret.yaml
- test/e2e/data/cluster-templates/azure-aks-topology.yaml
- test/e2e/data/cluster-templates/azure-rke2-topology.yaml
- test/e2e/helpers.go
- test/e2e/specs/etcd_snapshot_restore.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
- test/framework/apply.go
This adds e2e testing for the Azure/RKE2 ClusterClass.
Note that the `v1.31.1+rke2r1` version is hardcoded, as it depends on the Azure cloud provider ClusterResourceSet.
There's no way to make this dynamic at the moment. 
This would need a refactor to use CAAPF for both documentation and testing, maybe.
Test run: https://github.com/rancher/turtles/actions/runs/13918769837
**Checklist**:
> Add Azure + RKE2 ClusterClass e2e test

- test/e2e/data/cluster-templates/docker-kubeadm.yaml
- test/e2e/data/cni/kindnet.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
- test/e2e/suites/import-gitops-v3/suite_test.go
kind/refactor
This PR switches CAPD+kubeadm cluster test to use clusterclass.
Fixes #1152 
One problem that needs to be addressed is that after the git repo is deleted, all dependent resources except ClusterClass are deleted. I am not sure yet why ClusterClass is retained.
**Checklist**:
> Switch CAPD+Kubeadm test to clusterclass in e2e

- test/e2e/data/cluster-templates/gcp-gke.yaml
As per [CRD](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpmanagedcontrolplanes.yaml#L69), added this field to name GKE cluster properly.
It would avoid naming of GKE cluster as `capg-*`
Fixes #
**Checklist**:
> Add clusterName in GCPManagedControlPlaneSpec e2e template

- examples/examples.go
- test/e2e/helpers.go
- test/e2e/specs/etcd_snapshot_restore.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Embed example clusterclasses in e2e suite, this should the code more readable
Fixes #
**Checklist**:
> Embed example clusterclasses in e2e suite

- test/e2e/specs/import_gitops_mgmtv3.go
- test/go.mod
- test/go.sum
This PR tries to address the issues with CAPI Clusters not being deleted for some e2e tests.
Fixes #
**Checklist**:
> Fix e2e Cluster deletion failures

- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- internal/controllers/clusterctl/config.yaml
Keep original `CAAPF` `CAPIProvider` name, since this change has issues with deletion of the previous, and is mostly cosmetical.
Fixes #1206 
**Checklist**:
> Keep fleet addon CAPIProvider name

- .github/workflows/e2e-long.yaml
When the current e2e nightly workflow runs automatically via `schedule`, the `inputs` do not exist at all because `schedule` does not support `inputs`. Since `scheduled` runs do not have `inputs`, we need to handle this explicitly to avoid unexpected behavior by setting explicit defaults in workflow. This change ensures `skip_resource_cleanup` and `skip_deletion_test` always have a default value (`false`) when the workflow is triggered automatically (e.g., via `schedule`).
Fixes #1217 
An example of successful e2e nightly run with this patch: …
> Fix nightly GHA inputs referenced in e2e_import_gitops_v3 test

- .github/workflows/golangci-lint.yaml
- .golangci.yml
- Makefile
- api/rancher/management/v3/doc.go
- api/rancher/provisioning/v1/doc.go
- internal/controllers/clusterctlconfig_controller.go
- internal/controllers/import_controller_v3.go
- internal/controllers/uiplugin_controller.go
- internal/sync/provider_sync.go
- internal/sync/secret_mapper_sync.go
- internal/sync/secret_sync.go
- internal/test/helpers/envtest.go
This PR fixes a few issues with the golangci-lint v2 [migration](https://golangci-lint.run/product/migration-guide/).
I ran the `migrate` command to convert the existing config.
Some new rule seem to be added by `staticcheck` linter, which I fixed.
This PR should replace: https://github.com/rancher/turtles/pull/1227
Fixes #
**Checklist**:
> Bump golangci-lint to v2

- .github/workflows/test_chart.yaml
- test/testenv/rancher.go
While installing Cert-Manager, I noticed deprecation warnings in the lint test chart due to the use of the deprecated [installCRDs](https://cert-manager.io/docs/releases/release-notes/release-notes-1.15/#other-cleanup-or-flake-1) option.
This patch replaces `installCRDs=true` with the recommended `crds.enabled=true` and `crds.keep=true` options, ensuring:
- CRDs are installed as part of the Helm deployment (`crds.enabled=true`).
- CRDs remain in the cluster even after Cert-Manager is uninstalled (`crds.keep=true`), maintaining the previous behavior of `installCRDs=true`.
Fixes #
**Special notes …
> Replace deprecated `installCRDs` option with new Helm options

- examples/clusterclasses/vsphere/clusterclass-kubeadm-example.yaml
- examples/examples.go
- test/e2e/const.go
- test/e2e/data/cluster-templates/vsphere-kubeadm-topology.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
kind/feature
Swithc vSphere + Kubeadm test case to ClusterClass.
Fixes #1154
vSphere + Kubeadm requires a CNI to be installed for the machines to be functional but installing Calico while on the VPN that gives access to vSphere is problematic because there seems to be a proxy that is redirecting to a different site when trying to reach the Helm repository. This will prevent this test from passing even though the cluster is provisioned. The moment Calico is installed it gets properly imported.
**While we find a solution, this PR uses the "legacy" approach for installing Calico in the workload cluster via `ClusterResourceSet`. This is not the ideal option for re-usability but it's …
> feat: switch capv+cabpk test to clusterclass

- test/e2e/const.go
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
We recently starting moving clusterclass definitions in directories grouped by infrastructure providers and apply them in tests  via Fleet. Since we keep clusterclasses for both Kubeadm and RKE2 providers in the same directory (see example [here](https://github.com/rancher/turtles/tree/e2f1e2a35e5a6b3920cb127ca26439bca69b6ca7/examples/clusterclasses/vsphere)), if a test targets RKE2, it will fail during test setup because the Kubeadm definitions that are also being applied (but not used by the test), are missing from the management cluster. 
Let me know if you prefer other alternatives to address this.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
> :seedling: Deploy KCP and CABPK in test to prevent errors

- .github/workflows/e2e-long.yaml
Cleaning this up as it is creating more troubles handling this input than anything else.
I also don't find this functional in the first place, since we are not meant to keep resources running. This will have terrible consequences to any next run of the job, if the resources are not manually cleaned (and properly) after, which no one can guarantee and has no indication anywhere.
Therefore the nightly job should always delete resources consistently.
A log trail can be used for troubleshooting in case of errors, otherwise it is already possible to investigate and debug issues while the test are running, since there are abundant timeouts to wait for.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> Do not allow skip resources cleanup for nightly tests

- examples/applications/cni/calico/helm-chart.yaml
This is a workaround to prevent Fleet failing installing all charts when the Rancher `agent-tls-mode` is set to Strict (default)
Fixes #
**Checklist**:
> Add insecureSkipTLSVerify to Calico HelmApp

- examples/clusterclasses/azure/clusterclass-rke2-example.yaml
- test/e2e/specs/import_gitops_mgmtv3.go
This PR adds an additional check to verify the CAPI Clusters have the `Ready` condition.
This is to ensure they are fully provisioned.
It can be otherwise that the test will succeed only if the first control plane node is initialized, but all the others fail to join.
Did a first run without editing the Azure RKE2 Class, and it does fail as expected:
https://github.com/rancher/turtles/actions/runs/14360104898/job/40259416000
```
[FAILED] Timed out after 2100.001s.
CAPI Cluster should be Ready
Expected success, but got an error:
<*errors.errorString | 0xc0008d0aa0>: 
Cluster is not Ready
{
s: "Cluster is not Ready",
}
```
Running a second one (expected to succeed) after I added back the `registrationMethod: internal-first` to the Class: …
> Ensure Cluster is Ready in e2e tests

- examples/clusterclasses/azure/clusterclass-rke2-example.yaml
Thanks to @valaparthvi we found that `eastus` and `eastus2` do not have the default Community image we use.
Not sure if it was removed recently or I made a mistake building the original list. 
Either way better remove these to prevent errors.
Fixes #
**Checklist**:
> Remove locations where the community image is not present

- test/e2e/const.go
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Adding example with ClusterClass for Docker with Kubeadm and RKEv2 and Fleet bundle to install CNI
Issue: https://github.com/rancher/turtles/issues/1212
Issue: https://github.com/rancher/turtles/issues/1211
Fixes #
**Checklist**:
> Enable Fleet bundles for Docker in e2e

- examples/applications/ccm/aws/fleet-bundle.yaml
- examples/clusterclasses/aws/clusterclass-kubeadm-example.yaml
- test/e2e/const.go
- test/e2e/data/cluster-templates/aws-kubeadm-topology.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Add CAPA/CABPK ClusterClass example and cover cluster provisioning from this class in E2E tests.
Fixes #1278
Sample nightly E2E run: https://github.com/rancher/turtles/actions/runs/14578369518
**Checklist**:
> feat: add capa+cabpk clusterclass example and test

- test/e2e/data/cluster-templates/vsphere-kubeadm-topology.yaml
- test/e2e/data/cluster-templates/vsphere-rke2-topology.yaml
> Update kube-vip image for vSphere example

- charts/rancher-turtles/templates/addon-provider-fleet.yaml
Only use CAAPF ConfigMap sync if Rancher is installed.
Fixes #
**Checklist**:
> Use rancherInstalled value for FleetAddon ConfigMap sync

- test/e2e/config/operator.yaml
- test/e2e/data/cluster-templates/aws-ec2-rke2-topology.yaml
Looks like AWS/RKE2 tests are intermittently failing and the workload seems to have a very high CPU usage. In some of executions where an error occurs, the cluster is provisioned successfully, the Rancher agent is deployed and validated and the cluster is fully functional. Then, before finishing all checks, it just stops responding. This would also explain why this error happens randomly and some tests just pass.
To remediate this, we can go up in the size of the EC2 instances used. To avoid increasing costs for AWS/Kubeadm, where we don't encounter this issue, a new variable is added to set the machine type for AWS/RKE2 only.
Fixes #
Let's run a full nightly E2E to validate that …
> test: increase cpu for aws/rke2 test

- examples/clusterclasses/azure/clusterclass-aks-example.yaml
Just a smaller quality of life changes. 
By default Azure creates a randomized resource group for AKS nodes, for example: `MC_my-resource-group-w77s7_westeurope`. 
By reusing the already defined `resourceGroup` variable, we can better scope this group name. 
Additionally, this change should now also cover the `resourceGroup` in the [cleanup job](https://github.com/rancher/turtles/blob/main/.github/workflows/e2e-cleanup.yaml#L42), which is not the case currently due to the `MC_` prefix.
Fixes #
**Checklist**:
> Use predictable resourceGroup for AKS nodes

- test/e2e/config/operator.yaml
- test/e2e/data/cluster-templates/aws-ec2-rke2-topology.yaml
- test/e2e/data/cluster-templates/azure-rke2-topology.yaml
Bump RKE2 version in e2e, this is needed to use a newer version of CoreDNS and reduce the number of flakes for cases where rancher server URL can't be resolved.
✅  https://github.com/rancher/turtles/actions/runs/14725052460
Fixes #
**Checklist**:
> Bump RKE2 version in e2e

- charts/rancher-turtles/values.yaml
- feature/feature.go
- internal/controllers/import_controller_v3_test.go
Promoted agent-tls-mode to beta so it is now enabled by default. Note that the tests do not validate the behaviour when the mode is set to `strict` as that would also require a custom CA to be used which complicates test setup.
Fixes #1318 
Related docs PR: https://github.com/rancher/turtles-docs/pull/294
**Checklist**:
> :seedling: Promote agent-tls-mode feature to beta

- examples/clusterclasses/vsphere/kubeadm/clusterclass-kubeadm-example.yaml
- examples/clusterclasses/vsphere/rke2/clusterclass-rke2-example.yaml
- test/e2e/data/cluster-templates/vsphere-kubeadm-topology.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
Refactor the Kubeadm vSphere class to align with the RKE2 one.
This also includes usage of VSphereClusterIdentity.
e2e test has also been added to the suite (previously skipped).
Test run: https://github.com/rancher/turtles/actions/runs/14776183446/job/41484866481
Docs: https://github.com/rancher/turtles-docs/pull/297
Fixes https://github.com/rancher/turtles/issues/1200
**Checklist**:
> vSphere Kubeadm Class improvements

- internal/controllers/clusterctl/config.yaml
- internal/controllers/clusterctl/config_test.go
- test/e2e/suites/chart-upgrade/chart_upgrade_test.go
- updatecli/updatecli.d/manifest.yaml
Clusterctl overrides didn’t include `CAAPF` source at this point. This change adds override to the list of other providers with image overrides, and adds e2e tests on top.
Fixes #1340 
**Checklist**:
> Override CAAPF provider image source to downstream one

- internal/sync/client.go
- internal/sync/core.go
- internal/sync/core_test.go
The issue is related to the order of provider creation. Initially, a `create` call is made on the synced manifest, resulting in an empty spec for the resource in the CAPI Operator case. This leads the provider to install the latest version if it detects the event before the subsequent `patch`, and if user specified version of the provider differs, it attempts a downgrade later (which is not allowed).
To resolve this, the `create` operation should be moved to the `apply` scenario. Alternatively, an SSA patch can be used and the `create` operation removed, but this approach reintroduces flakes in the `Updated to latest %s version` test.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will …
> Perform create only after sync operation

- .github/workflows/e2e-long.yaml
- test/e2e/specs/etcd_snapshot_restore.go
- test/e2e/specs/import_gitops_mgmtv3.go
This change would automate the nightly run for every PR, instead of requiring the reviewer to attach one automatically. This check can be made mandatory to prevent merges with failing long e2e tests later, if needed.
Such change would eliminate situations when several independent PRs are merged simultaneously, and all have attached successful nightly runs, but in combination they cause nightlies to fail.
Merge queues perform checks in a sequential order, with all PRs currently in the queue rebased on top of each other. Therefore, it follows the established concurrency pattern, but in order to eliminate conflicts between regular nightly runs and merge queue ones, the `concurrency: ci_e2e_tests` is lifted, and each cluster uses a unique name now.
In …
> Enable long run in pre-submits via the merge-queue

- internal/controllers/import_controller_v3_test.go
- scripts/turtles-quickstart.sh
- test/e2e/data/rancher/rancher-setting-patch.yaml
- test/testenv/turtles.go
- tilt/project/Tiltfile
This PR removes usage of insecure-skip-verify from test (and all other) environment. 
The import now uses the `agent-tls-mode` from Rancher. The PR also reverts this setting to the default 'Strict' value.
Test run: https://github.com/rancher/turtles/actions/runs/14975519278
Fixes #1268
Fixes #1370
**Checklist**:
> Remove insecure-skip-verify usage from test environment

- tilt/project/Tiltfile
Cleanup from #1368
Since the insecure-skip-verify option is no longer useful and has been removed, I simply renamed this field to a more appropriate name `verbose`, since it still increases verbosity.
Fixes #
**Checklist**:
> Remove insecure-skip-verify option from Tiltfile

- charts/rancher-turtles/values.schema.json
- charts/rancher-turtles/values.yaml
Increase memory limits to allow the CAPI operator deployment to complete the reconcile on CAPZ provider components without getting OOMKilled after surpassing 150Mi limit set currently.
Fixes #1204 
**Checklist**:
> Set higher memory limits for the CAPI Operator

- scripts/turtles-dev.sh
- scripts/turtles-quickstart.sh
Cluster import fails when ngrok is used and Rancher is served on a different Ingress.
The easiest solution is to set Rancher agent-tls-setting to SystemStore, assuming the certificate will be trusted.
Alternatively the agent-tls-setting can be kept to Strict, but the tls-rancher-ingress cert needs to be used instead.
Fixes #
**Checklist**:
> Use SystemStore agent-tls-setting with ngrok

- exp/day2/go.mod
- exp/day2/go.sum
- internal/controllers/clusterctl/config.yaml
https://github.com/rancher/cluster-api-provider-rke2/releases/tag/v0.16.0
Fixes #
**Checklist**:
> Bump CAPRKE2 to v0.16.0

- .github/workflows/golangci-lint.yaml
- internal/controllers/capiprovider_controller.go
Equivalent to what we already did in CAPRKE2 https://github.com/rancher/cluster-api-provider-rke2/pull/666. This PR updates Go linter and fixes format errors raised by the new version.
Fixes #
**Checklist**:
> chore: bump golangci lint action to 8

- examples/applications/ccm/azure/helm-chart.yaml
- examples/applications/cni/calico/helm-chart.yaml
- examples/clusterclasses/azure/kubeadm/clusterclass-kubeadm-example.yaml
- test/e2e/config/operator.yaml
- test/e2e/const.go
- test/e2e/data/cluster-templates/azure-kubeadm-topology.yaml
- test/e2e/suites/import-gitops-v3/import_gitops_v3_test.go
kind/enhancement
This PR adds Azure Kubeadm Clusterclass example and related test.
- Modify the CCM and CNI to refer the new class.
- Add Azure Kubeadm ClusterClass example that can be referred in documentation (documentation change pending)
- Add e2e test.
Fixes #1330
I will work on documentation for this soon.
Issues discovered while working on the PR:
- [Can not provision a second Azure Cluster while one already exists](https://github.com/rancher/turtles/issues/1403)
- [Can not provision Kubeadm cluster with multiple control plane …
> Add Azure kubeadm clusterclass example

- test/framework/rancher_helpers.go
This PR prints the (Rancher) kubeconfig secret key to better determine test failures.
Fixes #
**Checklist**:
> Print e2e Rancher kubeconfig secret key

- .github/workflows/run-vsphere-tests.yaml
- examples/clusterclasses/vsphere/rke2/clusterclass-rke2-example.yaml
- test/e2e/config/operator.yaml
- test/e2e/data/cluster-templates/vsphere-rke2-topology.yaml
This PR adds support for docker.io registry authentication with the vSphere/RKE2 ClusterClass.
Part of: #1408
Blocked by: https://github.com/rancher/cluster-api-provider-rke2/pull/673
Test run: https://github.com/rancher/turtles/actions/runs/15463788073/job/43531020953
Tested manually:
Fixes #
**Checklist**:
> [vSphere][RKE2] Add docker.io registry authentication support

- examples/clusterclasses/vsphere/rke2/clusterclass-rke2-example.yaml
Fix for `kube-vip` in clusterClass CAPV RKE2 example.
With original `kube-vip` static pod manifest location there was one pod running on the first control plane only so in case the first CP went down for whatever reason the cluster become unreachable (because kubevip:6443 was assigned only to the first node) and leader election did not work as there were no other kube-vip pods running on other CPs.
**BEFORE**
```
kubectl get pod kube-vip -n kube-system
NAME       READY   STATUS    RESTARTS   AGE
kube-vip   1/1     Running   0          2d8h
```
I fixed that by placing the kube-vip manifest into right location and now all the CPs have their own kube-vip pod running and leader elections is working as expected. After turning off the first CP (the one …
> Fix kube-vip static pod location and add a label

- docs/release.md
- examples/README.md
This PR introduces the capability to run the examples CLI tool directly using `go run` from the module path, without requiring a local clone of the repository. This is particularly useful for quickly applying `ClusterClass` examples with applications.
- Add a note to [documentation](docs/release.md) to include tagging the `examples` directory during releases. This ensures that specific version of the examples CLI is available with the new release.
- Add a README section which explains how to use the `go run` command with `@latest` (available already) or with specific tag (available after release including these changes) to apply examples from CLI.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` …
> Add ability to run examples CLI with `go run` from tag

- examples/clusterclasses/aws/kubeadm/clusterclass-kubeadm-example.yaml
Adds AMI ID optional patch in AWS Kubeadm ClusterClass, providing ability to set custom AMI for [unsupported regions](https://cluster-api-aws.sigs.k8s.io/topics/images/built-amis#supported-aws-regions) (eg. ap-south-2) and corresponding Kubernetes version. 
Existing cluster template unchanged as it uses already [published](https://github.com/rancher/turtles/blob/main/test/e2e/config/operator.yaml#L57) AMI for the region.
Fixes #
**Checklist**:
> Add AMI ID optional variable in AWS Kubeadm Class

- examples/clusterclasses/azure/kubeadm/clusterclass-kubeadm-example.yaml
- examples/clusterclasses/azure/rke2/clusterclass-rke2-example.yaml
This PR fixes the fixed `natGateway` name. This issue prevented to have two clusters deployed on the same namespace, as the statically named `node-natgateway` would collide after first provisioning.
The PR prefixes the cluster name to all network resources, to avoid collisions in one namespace:
```bash
> kubectl get clusters
NAME            CLUSTERCLASS            PHASE         AGE    VERSION
azure-kubeadm   azure-kubeadm-example   Provisioned   8m4s   v1.31.1
azure-rke2      azure-rke2-example      Provisioned   12m    v1.32.4+rke2r1
```
Test run: https://github.com/rancher/turtles/actions/runs/15583359625 (don't mind the unrelated failure)
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …
> Fix Azure classes network templating

- .github/workflows/run-vsphere-tests.yaml
- test/e2e/specs/etcd_snapshot_restore.go
- test/e2e/specs/import_gitops_mgmtv3.go
- test/e2e/suites/v2prov/v2prov_test.go
- test/framework/rancher_helpers.go
This PR adds the needed ginkgo node for parallel test execution. It's a little bit faster now.
I also consume the ClusterProxy directly, instead of just the Client, to avoid cache and print some maybe useful information on the kubectl setup. This to guarantee we are not somehow using a different kubeconfig path when the test presents flakiness.
Relates to #1392 
Test run: https://github.com/rancher/turtles/actions/runs/15752888760
Fixes #
**Checklist**:
> Increase ginkgo nodes for parallel vSphere e2e

- docs/release.md
Document missing pre-documentation release publishing to update component versions in Turtles docs
Fixes #
**Checklist**:
> 📖 Document a missing pre documentation publishing step

- internal/controllers/clusterctl/config.yaml
Bump CAPG from v1.9.0 to v1.10.0
Fixes #
**Checklist**:
> chore: bump cluster-api-provider-gcp to v1.10.0

- test/framework/git_helper.go
Fixes panic in long e2e suite due to adhering to new linter rules.
Test run: https://github.com/rancher/turtles/actions/runs/16070984765
Fixes #
**Checklist**:
> Fix panic on nil error in `defaultToCurrentGitRepo`

- examples/clusterclasses/azure/rke2/clusterclass-rke2-example.yaml
- test/e2e/data/cluster-templates/azure-rke2-topology.yaml
This PR leverages new CAPZ [security groups functionality](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5525) to properly configure the control plane loadbalancer for RKE2. 
The `internal-first` registration method is no longer needed, and we can default to `control-plane-endpoint` instead.
Test run: https://github.com/rancher/turtles/actions/runs/16164349249
Doc: https://github.com/rancher/turtles-docs/pull/339
Fixes #
**Checklist**:
> Use control-plane-endpoint RKE2 registrationMethod with Azure

- updatecli/updatecli.d/manifest.yaml
Turtles no longer uses CAPI operator helm chart, so regular CAPIO updates are carried by the dependabot dependency bumps in `go.mod` file. This change cleans up outstanding parts.
Fixes #
**Checklist**:
> Remove CAPIO from updatecli

- internal/sync/azure_provider_sync.go
- internal/sync/provider_sync_test.go
Just a random cleanup I noticed. 
This argument is deprecated since 0.19.0: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5416
Fixes #
**Checklist**:
> Remove deprecated bootstrap-config-gvk capz argument

- internal/controllers/clusterctl/config.go
- internal/controllers/clusterctl/config.yaml
- internal/controllers/clusterctlconfig_controller.go
- internal/controllers/operator_reconciler.go
- scripts/turtles-dev.sh
- test/e2e/const.go
- test/e2e/data/capi-operator/clusterctlconfig.yaml
- test/testenv/operator.go
- test/testenv/turtles.go
This PR adds an initial phase to Provider reconciliation, so that it waits for the mounted config (`/config/clusterctl.yaml`) to be synced. Note that it may take [a few minutes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically) for the sync to happen, all the CAPIProviders will be stuck in "Provisioning" for the time being. This is not great, but certainly better than trying to deploy providers **without** overrides (and then patch them).
The sync itself is left untouched, so it will still load the in-memory embedded config and apply changes from the user-defined ClusterctlConfig resource, if any.
I added some rudimentary image override validation in e2e, since we are …
> Wait for mounted clusterctl config to be synced

- .github/workflows/run-vsphere-tests.yaml
Cleans up docker artefacts after performing e2e tests / without this we would be hitting `no space left` soon.
Fixes #1540
* I decided to use `run:` block for the cleanup as the self-hosted runner is only temporary and should be replaced by hosted runner where the cleanup won't be needed.
* Cleans up all docker resources: containers, images, docker build cache, volumes and networks.
* Re-creates kind network needed by kind cluster.
**Checklist**:
> Cleanup vsphere self-hosted runner

- exp/day2/go.mod
- exp/day2/go.sum
- internal/controllers/clusterctl/config.yaml
Bump Cluster API Provider RKE2 to latest patch version `v0.18.1`.
Fixes #
**Checklist**:
> chore: bump cluster-api-provider-rke2 to v0.18.1

- charts/rancher-turtles/templates/post-upgrade-job.yaml
- charts/rancher-turtles/values.yaml
This PR adds a post-upgrade hook that removes all CAPI Operator provider resources from the cluster.
Fixes #1548 
To test this, run `RELEASE_TAG=v0.22.0 make release` then upgrade an existing Turtles installation by running 
```
helm upgrade rancher-turtles -n rancher-turtles-system --reset-then-reuse-values ./out/package/rancher-turtles-0.22.0.tgz --debug
```
to install the new chart version.
The `kubectl` image could not be used as it is distroless. 
**Checklist**:
> feat: Add post-upgrade hook that deletes all CAPI Operator provider resources

- api/v1alpha1/capiprovider_types.go
- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- charts/rancher-turtles/templates/core-provider.yaml
- charts/rancher-turtles/templates/rancher-turtles-components.yaml
- charts/rancher-turtles/templates/rke2-bootstrap.yaml
- charts/rancher-turtles/templates/rke2-controlplane.yaml
- charts/rancher-turtles/values.schema.json
- charts/rancher-turtles/values.yaml
- config/crd/bases/turtles-capi.cattle.io_capiproviders.yaml
- internal/controllers/operator_reconciler.go
- internal/controllers/operator_reconciler_test.go
- test/e2e/config/operator.yaml
- test/e2e/const.go
- test/e2e/data/test-providers/capv-provider-no-ver.yaml
- test/e2e/data/test-providers/clusterctlconfig-updated.yaml
- test/e2e/data/test-providers/clusterctlconfig.yaml
- test/e2e/data/test-providers/namespace.yaml
- test/e2e/data/test-providers/unknown-provider.yaml
- test/e2e/suites/capiprovider/capiprovider_test.go
- test/e2e/suites/capiprovider/suite_test.go
This PR does mainly two things: 
- Allows the upstream provider reconciler to patch the CAPIProviderSpec. It's more straightforward to simply rely on the upstream business logic for all the generic provider fields.
- Introduces a new feature `EnableAutomaticUpdate` on CAPIProviders. This feature is needed to clearly distinguish whether the user wants the providers to be automatically updated, or not. Previously this was done by leaving the CAPIProvider.Spec.Version blank. The behavior is going to change in the following way:
1. Users installing the default providers from the chart will not be affected (core, rke2, fleet) and will continue to experience automatic updates on Turtles updates (on ClusterctlConfig updates). 
2. Users who pinned the …
> Implement CAPIProvider EnableAutomaticUpdate toggle

- Makefile
- hack/make-release-notes.sh
This PR should fix the release notes not being generated anymore. 
The notes binary is now built using the supported CAPI_VERSION.
Note that the hardcoded `-branch=main` may bring issues when generating notes from a release branch, adding more than expected. This entire process probably needs some more toughts/refactor. This PR is mostly a quick fix so that CI can continue.
Fixes #
**Checklist**:
> Fix release notes generation

- test/e2e/README.md
This PR originates from a series of failed e2e tests like: https://github.com/rancher/turtles/actions/runs/17232674791/job/48907585304?pr=1653
Turns out running these tests locally requires Fleet GitRepos to be configured correctly, requiring `SOURCE_REPO` and `GITHUB_HEAD_REF` to be explicitly set.
However, this was not the case before. 
The following should also work by default:
```bash
MANAGEMENT_CLUSTER_ENVIRONMENT=isolated-kind TAG=v0.0.1 GINKGO_LABEL_FILTER=short make test-e2e
```
but this now leads to:
```yaml
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
name: docker-cluster-classes-regular-6pw6xc
namespace: fleet-local
spec:
repo: https://github.com/rancher/turtles.git
branch: improve_local_test_doc
forceSyncGeneration: 1 …
```
> Clarify SOURCE_REPO and GITHUB_HEAD_REF on short e2e tests

- api/v1alpha1/conditions_consts.go
- charts/rancher-turtles/questions.yml
- charts/rancher-turtles/templates/deployment.yaml
- charts/rancher-turtles/values.yaml
- feature/feature.go
- internal/controllers/operator_reconciler.go
This PR adds logic to patch objects defined in a provider's manifest leveraging a new CAPI Operator functionality that allows passing a custom alter components function which is executed during the `Fetch` phase.
A new feature gate `no-cert-manager` is added, and this logic is only applied if set to `true` (it is an opt-in action, defaults to `false`). The following operations are performed if enabled.
This is implemented in function `patchProviderManifestFn`, which retrieves the name of the secret from the `Certificate` resource and annotates the webhook service (e.g. `capi-webhook-service` with:
`need-a-cert.cattle.io/secret-name: <secretName>`
This is implemented in function `removeCertManagerFn`:
- Removes annotation …
> feat: let wrangler manage certs

- .github/workflows/test_chart.yaml
- charts/rancher-turtles/templates/addon-provider-fleet.yaml
- charts/rancher-turtles/templates/pre-delete-job.yaml
- charts/rancher-turtles/templates/rke2-bootstrap.yaml
- charts/rancher-turtles/templates/rke2-controlplane.yaml
Add helm policy keep to installed providers in Turtles chart. That should help users migrate once we remove these templates from Turtles chart.
Fixes https://github.com/rancher/turtles/issues/1719
**Checklist**:
> Add helm policy keep to installed providers

- .github/workflows/backport-pr.yaml
We can make use of dashboard backport PR meanwhile we will have something [common](https://github.com/rancher/rancher/issues/52006) for all repos. Taken from https://github.com/rancher/dashboard/blob/master/.github/workflows/port-pr.yaml
Related to: #1746
**Special notes for your reviewer**: I have not tested it in my fork since it tries to reach org members and check if you are a member in the org, however it should most probably work as is out of the box. 
**Checklist**:
> Add backport automation GitHub workflow

- charts/rancher-turtles/values.yaml
Follow-up to: https://github.com/rancher/turtles/pull/1783 to cleanup leftover clusterclass-operations from values.yaml
Backport of #1800 
Fixes #
**Checklist**:
> [release/v0.25] remove clusterclass-operations from values.yaml
